### ISSUE TITLE
Support SPAs

### ISSUE THREAD

**Issue by MuhammadM1998** [harlan-zw/nuxt-seo#103]
### Details

I've set up the v2 of the module in a fresh project and it's working properly. For the below config the `name` is picked up correctly in the title so it's working.

```js
site: {
  name: "M98",
  url: "https://m98-test.vercel.app/",
},
```

As soon as I add `ssr: false` to the config and run the dev server again the title breaks, it becomes `%site.name%` instead.

Am I doing something wrong or the module works with SSR only?

**Comment by harlan-zw** [comment]
Hi @MuhammadM1998, the v2 is currently in beta and is only being actively tested with SSR apps at this time. It will be available for SPAs at some point but it's not a priority as SPA sites are inherently not SEO-friendly.

**Comment by MuhammadM1998** [comment]
@harlan-zw Thanks for the help and for the great module 🙏 If I may ask is there any woraround to set the title until its stable or will I have to remove the module?

**Comment by harlan-zw** [comment]
You should just be able to set a title template within your app.vue or the page. Can you confirm your Nuxt version?

**Comment by MuhammadM1998** [comment]
I'll try that and get back to you. I'm using the latest nuxt `3.7.1`

**Comment by DamianGlowala** [comment]
Not sure if this is related, but when I run `nuxi generate`, the page title remains `%siteName` until the page is loaded (Nuxt v3.7.2).

**Comment by harlan-zw** [comment]
> Not sure if this is related, but when I run `nuxi generate`, the page title remains `%siteName` until the page is loaded (Nuxt v3.7.2).

I think this might be a breaking change that isn't documented in the migration. You'll need to change it to `%site.name`, I may add support for both before the stable release

**Comment by harlan-zw** [comment]
> Site name is set through the runtime config though. Do you mean manually replacing it in the generated bundle for the time being?

Which version are you using? In v2 we no longer inject the entire runtime config as template params, just select keys.

If you're using the beta, then `2.0.0-beta.30` should fix your issue.

**Comment by harlan-zw** [comment]
SPAs should have slightly better support in [v2.0.0-beta.37](https://github.com/harlan-zw/nuxt-seo-kit/releases/tag/v2.0.0-beta.37) where the site config will be injected into the non-ssr page templates.

**Comment by a-dubiel** [comment]
@harlan-zw is there a way to make `og-image` module work with [Nuxt hybrid rendering](https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering)? For example, my app is set to `ssr: false` but some of my routes are set ot `ssr: true`.  I want these routes to work with this module only.

Thank you so much for your work.

**Comment by harlan-zw** [comment]
This is not possible, the Nuxt server needs to be available to generate the og image option payload and render the image.

Going to close this as it's a bit off topic.

If you have any specific issues with SPA in the v2 stable please make a new issue.
