### ISSUE TITLE
Are nuxt seo kit not working correctly with language like Korean

### ISSUE THREAD

**Issue by bangrobe** [harlan-zw/nuxt-seo#113]
### Describe the bug

I'm not sure there are any advanced settings for these kind of languages. It display correctly if I don't use SEO kit.  My posts have many languages in post title.

https://i.imgur.com/gr9rRlv.png

And are there any advanced settings for Breadcrumbs? I want to display something like Home/Category-Name/Post-Name. 

Thank everyone. 

### System / Nuxt Info

```Shell
Nuxt project info:                                                                                                                      5:22:31 PM

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.5.1
- Builder:          -
- User Config:      modules, app, devtools, runtimeConfig, pinia, colorMode, extends
- Runtime Modules:  @nuxt/ui@2.8.1, @pinia/nuxt@0.4.11
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
Hi @bangrobe 

I'm not too sure what the issue is exactly. It looks like you're trying to use korean characters within the URL. This is supported but the characters will always get encoded.

Can you confirm if this is the issue or something else?

Also I'd recommend using v2.
