### ISSUE TITLE
How to set dynamic site name with Nuxt Seo version 2.x?

### ISSUE THREAD

**Issue by stefanobartoletti** [harlan-zw/nuxt-seo#121]
### Details

This is probably related to #34 but specific to version 2.x of the module.

I currently have this configuration in my `layouts/default.vue` to dynamically set the site name, fetched from a CMS

```vue
<template>
  <div class="flex min-h-screen flex-col">
    <SeoKit :site-name="siteConfig.content.site_title" />
    <SiteHeader />
    <slot></slot>
    <SiteFooter />
  </div>
</template>

<script setup>
const siteConfig = await useAsyncStoryblok('config/site-config', {
  version: 'draft',
  resolve_links: 'url',
})
</script>
```

I also need to set the site title dynamically when using version 2, but the `SeoKit` component and composable are deprecated. I cannot find how to do this in the documentation (maybe it is there and it's only my bad :D ).

How can I do this?

**Comment by stefanobartoletti** [comment]
I tried to read the documentation more thoroughly, and according to this paragraph https://nuxtseo.com/site-config/guides/setting-site-config#programmatic-site-config-runtime it seems that what I'm trying to achieve could be done by the `updateSiteConfig` composable. The relative documentation page is not yet available though.

This is not extremely urgent, but can you please confirm that doing this is indeed possible b y that composable?

**Comment by harlan-zw** [comment]
Hi @stefanobartoletti, sorry for the delay.

You have quite a number of options in updating the site config, all of them start from using `updateSiteConfig`. The recommended approach would be using either a nitro or nuxt plugin or middleware.

Here's an example using a Nuxt server plugin.

```ts
// plugins/site-config.server.ts
import { defineNuxtPlugin, updateSiteConfig, useRequestURL } from '#imports'

export default defineNuxtPlugin({
  name: 'nuxt-site-config:overrides',
  enforce: 'post',
  setup() {
    const url = useRequestURL()
    if (url.origin.includes('subdomain.host.com')) {
      updateSiteConfig({
        url: url.origin,
        name: 'Subdomain',
        description: 'Subdomain description',
      })
    }
  },
})
```

Let me know if you have any questions on usage, will keep this open either way until it's properly documented.

**Comment by stefanobartoletti** [comment]
Thanks for your reply, I'll try this and let you know if it works in my current setup.

**Comment by harlan-zw** [comment]
Please see https://nuxtseo.com/site-config/guides/runtime-site-config, if you still have issues let me know!
