### ISSUE TITLE
301 redirection on each page

### ISSUE THREAD

**Issue by GuillaumeDgr** [harlan-zw/nuxt-seo#122]
### Describe the bug

Each time I visit any or my nuxt3 website url, a 301 redirection occurs and redirects to url/ with trailing slash at the end. This is really a problem for SEO matters...

I look for all topics about it but did not find any workable solution, pls help me!

Many thanks!
![Screenshot 2023-10-12 at 17 42 01](https://github.com/harlan-zw/nuxt-seo-kit/assets/29545767/ee59e282-4dd4-453b-8fa1-31e8a427c04a)
![Screenshot 2023-10-12 at 17 39 12](https://github.com/harlan-zw/nuxt-seo-kit/assets/29545767/f012347f-a8c3-4edf-96bd-0ac604359df6)

### Reproduction

https://devloop.dev/any-url

### System / Nuxt Info

```Shell
- Operating System: Darwin
- Node Version:     v19.1.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      site, modules, runtimeConfig, plugins, build, googleFonts, strapi, i18n, colorMode, gtag, image, vite, sitemap
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/google-fonts@3.0.2, @nuxtjs/strapi@1.9.3, @nuxtjs/i18n@8.0.0-rc.5, @nuxtjs/color-mode@3.3.0, @nuxt/image@1.0.0-rc.3, nuxt-icon@0.4.2, nuxt-gtag@0.5.9, nuxt-jsonld@2.0.8, nuxt-simple-robots@3.1.6, nuxt-simple-sitemap@3.4.0, vue-recaptcha/nuxt
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
Hey, could you try out 2.0.0-beta.38.

I think it's trying to redirect to the canonical URL but it's failing due to some proxying (?) issue.

**Comment by GuillaumeDgr** [comment]
Hi, thanks a lot, I'm using nuxt-simple-robots@3.1.6, nuxt-simple-sitemap@3.4.0, should I delete these modules and use only nuxt seo kit 2.0.0-beta.38 ?

**Comment by harlan-zw** [comment]
> Hi, thanks a lot, I'm using nuxt-simple-robots@3.1.6, nuxt-simple-sitemap@3.4.0, should I delete these modules and use only nuxt seo kit 2.0.0-beta.38 ?

Neither of these modules has any redirect logic in them. Are you sure it's not something on your server end?
