### ISSUE TITLE
Nuxt SEO module and Setting An Identity

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-seo#134]
### Details

Hello,

On this page, https://nuxtseo.com/nuxt-seo/guides/setting-an-identity, you tell this "As part of your identity, it's recommended to configure your social media links as well.".

Could the documentation have more info about this? what is the purpose and how is it used?

Thanks

**Comment by harlan-zw** [comment]
Agreed, I'm not entirely confident that I'll leave this page in for the v2 stable yet though. 

The purpose is to help Google generate this for your site quicker, but it's not guaranteed.

![image](https://github.com/harlan-zw/nuxt-seo-kit/assets/5326365/f9c40cf9-6874-4109-9857-86faadc1126f)
