### ISSUE TITLE
`og:title` is not changed when `titleTemplate` is changed in `nuxt.config.ts`

### ISSUE THREAD

**Issue by Hiratake** [harlan-zw/nuxt-seo#137]
### Describe the bug

When `titleTemplate` is changed in `nuxt.config.ts` , the value of `<meta property="og:title">` tag is not changed. The value of the `<title>` tag will be changed correctly.

If `titleTemplate` is changed using `useHead` , the value of `og:title` also seems to change correctly.

The following documents were used as references.
https://nuxtseo.com/nuxt-seo/guides/title-templates#changing-title-template

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ca65wt

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      app, devtools, modules
- Runtime Modules:  @nuxtseo/module@2.0.0-beta.44
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Thanks for reporting and sorry for the delay, should be fixed in next RC.
