### ISSUE TITLE
DevTools OpenGraph Tab Not Working (upstream)

### ISSUE THREAD

**Issue by MuhammadM1998** [harlan-zw/nuxt-seo#147]
### Describe the bug

Using the latest `2.0.0-beta.51`, the integration with Nuxt DevTools doesn't seem to work as expected.
I'm using `defineOgImage` in `App.vue` to apply a static og image to all pages. It gets added correctly but the devtools doesn't pick it up.

**OpenGraph (built in Devtools)**
The image doesn't get picked up in preview or details. It says it's missing `og:image` and other metatags although it's present in the website <head>.
![1](https://github.com/harlan-zw/nuxt-seo-kit/assets/86230182/db9aa425-67bb-4380-90b3-87644867605b)

**OG Image (Nuxt Seo OG Image module)**
It says there isn't a `defineOGImage` used in the app. Even if I use another `defineOGImage` in `pages/index` as instructed the message stays the same.
![2](https://github.com/harlan-zw/nuxt-seo-kit/assets/86230182/ec4f44b0-8c95-4caa-a106-916d59c2a9ef)

**Reproduction**
I've created a minimal reproduction repo (Devtools doesn't work in Stackblitz / Codeflow).
- Download the repo
- `pnpm i && pnpm run dev`
- Go to localhost:3000 and open the devtools
- Go to OpenGraph option. It says `image` og tags are missing but if you inspect the DOM you'll find them.
- Go to OG Image option. It says `defineOGImage` is not used while it's there in App.vue. Uncomment the `defineOGImage` in `pages/index.vue` and the message stays the same.

### Reproduction

https://github.com/MuhammadM1998/nuxt-seo-reproduction

### System / Nuxt Info

```Shell
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.9.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtseo/module@2.0.0-beta.51
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
> OpenGraph (built in Devtools)

There is a bug in the Nuxt DevTools OpenGraph tab that it's not showing it, the module itself is working correctly.

> OG Image (Nuxt Seo OG Image module)

This is because you're trying to use the previewer for a pre-existing image, this is not currently supported. I've made an issue here to track: https://github.com/harlan-zw/nuxt-og-image/issues/129.

**Comment by MuhammadM1998** [comment]
Thanks for clarifying. I'll post update If I found a solution to the OpenGraph module

**Comment by harlan-zw** [comment]
Will close this for now as there are already upstream issues for them.

DevTools: https://github.com/nuxt/devtools/issues/580, https://github.com/nuxt/devtools/issues/274
OG Image: https://github.com/nuxt-modules/og-image/issues/129
