### ISSUE TITLE
When I use the Changing Title Template to dynamically change the title, the title on the page is rendered correctly, but when viewing the source code, the title displays "%fieldName"

### ISSUE THREAD

**Issue by BenanaH** [harlan-zw/nuxt-seo#152]
## nuxt.config.ts

```typescript
import { defineNuxtConfig } from "nuxt/config";

export default defineNuxtConfig({
  ssr: true,
  devtools: { enabled: true },
  router: {
    routes: [
      {
        name: "case",
        path: "/case/:id",
        component: "pages/case.vue",
      },
    ],
  },
  site: {
    name: "zgwk",
    path: "/sitemap.xml",
    url: "https://xxx.com",
    defaults: {
      changefreq: "always",
      lastmod: new Date(),
    },
    generate: false,
  },
  app: {
    pageTransition: {
      name: "slide-right",
      mode: "out-in",
    },
    layoutTransition: { name: "layout", mode: "out-in" },
    head: {
      titleTemplate: "%routeName",
      charset: "utf-8",
      viewport:
        "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
    },
  },
  css: ["~/assets/css/basic.css", "~/assets/css/media.css"],
  build: {
    transpile:
      process.env.NODE_ENV === "production"
        ? [
            "naive-ui",
            "vueuc",
            "@css-render/vue3-ssr",
            "@juggle/resize-observer",
          ]
        : ["@juggle/resize-observer"],
  },
  vite: {
    optimizeDeps: {
      include:
        process.env.NODE_ENV === "development"
          ? [
              "naive-ui",
              "vueuc",
              "date-fns-tz/esm/formatInTimeZone",
              "jsonwebtoken",
            ]
          : ["jsonwebtoken"],
    },
    server: {
      fs: {
        strict: false,
      },
    },
  },
  nitro: {
    devProxy: {
      "/api": { target: "https://server.xxx.com:80/", changeOrigin: true },
    },
  },
  plugins: ["~/plugins/seo.js"],
  modules: [
    "@pinia/nuxt",
    "@pinia-plugin-persistedstate/nuxt",
    "@element-plus/nuxt",
  ],
  postcss: {
    plugins: {
      "postcss-pxtorem": {
        rootValue: 16,
        propList: ["*"],
        replace: true,
        mediaQuery: false,
        minPixelValue: 7.5,
      },
    },
  },
  extends: ["nuxt-seo-kit"],
});

```

## about-us.vue

```typescript
<script setup>
import { useRoute } from "vue-router";
let route = useRoute();
let seoData = ref();
const getSeoData = async () => {
  const response = await fetch(
    `https://client.zgwksz.com:443/api/cn/seo/getSeo`
  );
  const data = await response.json();
  let result = data.data.filter((item) => item.url == route.path);
  seoData.value = result;
  document.title = seoData.value[0].title;
  useHead({
    templateParams: {
      routeName: "My Abount Us",
    },
    titleTemplate: "%routeName",
    meta: [
      { name: "description", content: seoData.value[0].description },
      { name: "keywords", content: seoData.value[0].keywords },
    ],
  });
};

getSeoData();
</script>
```
## The page rendering is successful.
![image](https://github.com/harlan-zw/nuxt-seo/assets/43538540/007e8fb6-a226-44ab-bf13-efa55c9fe3b3)

## The source code is %routeName
<img width="1451" alt="image" src="https://github.com/nuxt/seo/assets/43538540/f0155c34-78ee-4327-aa7b-4649d65faa66">

**Comment by raphaelbernhart** [comment]
@harlan-zw 
FYI When the `titleTemplate` is not defined, there is also a "wrong" title shown.
I could reproduce this bug on Chrome and Brave.

Current stack:
```
nuxt@3.9.1
@nuxtseo/module@2.0.0-beta.55
```

Maybe related? [image](https://github.com/harlan-zw/nuxt-seo/assets/48283236/e257ee0c-05b1-45f9-8b8e-6aec16fcc9cd)

**Comment by harlan-zw** [comment]
The issue OP has is that you're setting the `routeName` template param async without awaiting it, the server does not wait for this promise to resolve before generating the template. 

I'd recommend awaiting it and also setting a default routeName within nuxt.config


@raphaelbernhart can you share some code?

**Comment by raphaelbernhart** [comment]
@harlan-zw Thanks for the reply :)

What code do you mean? I do not change the title somewhere dynamically.

Here is my config:
```
site: {
        url: "https://DOMAIN",
        name: "TITLE",
        description:
            'DESCRIPTION',
        defaultLocale: "de",
        currentLocale: "de",
        indexable: true,
        identity: {
            type: "Organization",
        },
        trailingSlash: true,
    },
```

**Comment by harlan-zw** [comment]
> FYI When the titleTemplate is not defined, there is also a "wrong" title shown.

I'm not sure what you mean by this, providing some code would give me some more context for what you're talking about.

**Comment by harlan-zw** [comment]
Please try @nuxtjs/seo@2.0.0-rc.3 :+1:

**Comment by raphaelbernhart** [comment]
> Please try @nuxtjs/seo@2.0.0-rc.3 👍

This release seems to fix the error...thanks :)

**Comment by BenanaH** [comment]
> OP 的问题是，您正在设置`routeName`模板参数异步而不等待它，服务器在生成模板之前不会等待此承诺解决。
> 
> 我建议等待它并在 nuxt.config 中设置默认的routeName
> 
> @raphaelbernhart你能分享一些代码吗？

```typescript
head: {
  templateParams: {
    routeName: "Default",
  },
  titleTemplate: "%routeName"
}
```

## aount-us.vue

```typescript
onMounted(async () => {
  useHead({
    templateParams: {
      routeName: "My Abount Us",
    },
    titleTemplate: "%routeName"
  });
});
```

What I actually want to say is that %routeName does not change in the source code when I jump to the page. For example, in the above code, when the page jumps to about-as, the title reality is still Default

If I don't set a default value in nuxt.config.ts, what will be displayed in the source code is %routeName.

**Comment by harlan-zw** [comment]
`onMounted` is only called client-side, so it would never appear in the source code (which is generated on the server)

**Comment by BenanaH** [comment]
> `onMounted` is only called client-side, so it would never appear in the source code (which is generated on the server)

Thanks for the reply👀
Before, I tried to directly use `useHead`, and in the source code it is still `%routeName`, like this:
```typescript
useHead({
  templateParams: {
    routeName: "My Abount Us",
  },
  titleTemplate: "%routeName"
});
```
I'm not very familiar with using the tool. So, does that mean 'useHead' can't modify the source code to the value set by the current page after the page jumps?
