### ISSUE TITLE
Can't install package via yarn / npm

### ISSUE THREAD

**Issue by andywillekens** [harlan-zw/nuxt-seo#153]
Getting the following error:

`An unexpected error occurred: "https://registry.yarnpkg.com/@nuxt%2fseo: Not found".`

I'm using the command `yarn add -D @nuxt/seo` as described [here](https://nuxtseo.com/nuxt-seo/getting-started/installation#setup) 

Same goes for `npm install -D @nuxt/seo`.

**Comment by harlan-zw** [comment]
Hi, sorry I was between migrating the docs and the package.

Please try `yarn add -D @nuxtjs/seo`, docs should be updated to reflect that.
