### ISSUE TITLE
OgImage not working without `path` (in Document Driven mode)

### ISSUE THREAD

**Issue by eunjae-lee** [harlan-zw/nuxt-seo#155]
### Describe the bug

Hi there 👋🏼 I'm trying to use `OgImage` for my project using Nuxt Content.

Even though Document Driven mode is on, OgImage is not working unless I explicitly add `path` property to the frontmatter.

![Screenshot 2024-01-05 at 22 35 38](https://github.com/harlan-zw/nuxt-seo/assets/499898/bbc398c9-7c43-43cd-aec8-4026101853e7)

Here is the demonstration of the issue:

https://github.com/harlan-zw/nuxt-seo/assets/499898/2f50beb0-7569-40a6-a77d-a42e325af136

Did I misunderstand it? Or did I misconfigured it? 🤔

### Reproduction

https://github.com/eunjae-lee/nuxt-seo-image-reproduction

### System / Nuxt Info

```Shell
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.6.7 - /opt/homebrew/bin/pnpm
    bun: 1.0.1 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 117.1.58.135
    Chrome: 120.0.6099.199
    Chrome Canary: 122.0.6228.0
    Safari: 17.2
```

**Comment by harlan-zw** [comment]
Thanks! Fix will be in the next Nuxt SEO RC

**Comment by eunjae-lee** [comment]
@harlan-zw Awesome. Thank you :D

**Comment by harlan-zw** [comment]
@nuxtjs/seo@2.0.0-rc.3 should be good :+1:

**Comment by eunjae-lee** [comment]
@harlan-zw what a speedy release. it's working very well. thanks so much 👍🏼
