### ISSUE TITLE
[nitro] [unhandledRejection] TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".wasm"

### ISSUE THREAD

**Issue by DidoMarchet** [harlan-zw/nuxt-seo#160]
### Describe the bug

Hi, when I install and configure nuxt-seo i get:
<img width="1040" alt="Screenshot 2024-01-09 at 12 49 58" src="https://github.com/harlan-zw/nuxt-seo/assets/38940340/29622d7a-9e67-44f7-bec2-9ae096bee937">

### Reproduction

Install the package and add it into the modules.

### System / Nuxt Info

```Shell
- Operating System: Darwin
- Node Version:     v21.5.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.0
- Builder:          -
- User Config:      apollo, app, build, css, delayHydration, devtools, experimental, formkit, gtm, i18n, modules, nitro, runtimeConfig, sitemap, sourcemap, ssr, vite
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5, @nuxtjs/seo@2.0.0-rc.4, @nuxtjs/apollo@5.0.0-alpha.7, @pinia/nuxt@0.4.11, @vite-pwa/nuxt@0.1.2, @formkit/nuxt@1.4.0, nuxt-delay-hydration@1.3.3, @zadigetvoltaire/nuxt-gtm@0.0.13
```

Thanks and kind regards,
Davide

**Comment by harlan-zw** [comment]
This is quite strange, would it be possible to provide a reproduction?

**Comment by DidoMarchet** [comment]
Hi! Sure!
this is a sandbox example.
After `npm i` and `npm run dev` if you wait that nuxt warms out you'll see the error in the terminal.

[CODESANDBOX](https://codesandbox.io/p/devbox/nuxtseo-zndfmq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrp0b56500073b6pbpmtyql2%2522%252C%2522sizes%2522%253A%255B54.56221198156682%252C45.43778801843318%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrp0b56400023b6pv1d1v65u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrp0b56500043b6pf6f3herd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrp0b56500063b6pe52nir24%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrp0b56400023b6pv1d1v65u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrp0b56400013b6pkw0uwp2c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrp0b56400023b6pv1d1v65u%2522%252C%2522activeTabId%2522%253A%2522clrp0b56400013b6pkw0uwp2c%2522%257D%252C%2522clrp0b56500063b6pe52nir24%2522%253A%257B%2522id%2522%253A%2522clrp0b56500063b6pe52nir24%2522%252C%2522activeTabId%2522%253A%2522clrp0dcm000d43b6ppyw7xupl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrp0b56500053b6p7etpkoh8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clrp0dcm000d43b6ppyw7xupl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fen%2522%257D%255D%257D%252C%2522clrp0b56500043b6pf6f3herd%2522%253A%257B%2522id%2522%253A%2522clrp0b56500043b6pf6f3herd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrp0cbcf00af3b6p9de3rh2q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrp0cbe7000ie1eif5cu3s84%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrp0cbcf00af3b6p9de3rh2q%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Kind regards,
Davide

**Comment by harlan-zw** [comment]
Thanks. So It seems like the initial error is also from codesandbox? 

The issue is that these kinds of dev environments use webcontainers that don't support native WASM, WASM is needed to properly render the images using Satori for the OG Image module. There is a workaround for Stackblitz, in that we load the wasm files as a file instead of a module. 

I've pushed up some logic to support `codesandbox` in the latest OG Image module (3.0.0-rc.29), it will be available in the next Nuxt SEO RC version

**Comment by DidoMarchet** [comment]
Hi, the codesandbox has the configuration I used in locale development. So the same error is in my environment.
But it appears only in the console and it's not a critical error.

Really thanks and kind regards!
