### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Shuyee11730** [harlan-zw/nuxt-seo#161]
### Details

When I executed yarn add -D @nuxtjs/seo in VSCode, an exception occurred. The error message is as follows:

yarn add v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning " > less-loader@11.1.3" has unmet peer dependency "webpack@^5.0.0".
warning " > @nuxt/devtools@1.0.6" has unmet peer dependency "vite@*".
warning "@nuxt/devtools > @nuxt/devtools-kit@1.0.6" has unmet peer dependency "vite@*".
warning "@nuxt/devtools > vite-plugin-inspect@0.8.1" has unmet peer dependency "vite@^3.1.0 || ^4.0.0 || ^5.0.0-0".
warning "@nuxt/devtools > vite-plugin-vue-inspector@4.0.2" has unmet peer dependency "vite@^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0".
warning "@nuxtjs/seo > @nuxtjs/sitemap > h3-compression@0.3.2" has unmet peer dependency "h3@^1.6.0".
warning "@nuxtjs/seo > @nuxtjs/sitemap > @nuxt/devtools-ui-kit > v-lazy-show@0.2.4" has unmet peer dependency "@vue/compiler-core@^3.3".warning "@nuxtjs/seo > nuxt-schema-org > @unhead/schema-org@1.8.9" has unmet peer dependency "unhead@>=1.8.8".
warning "@nuxtjs/seo > nuxt-schema-org > @unhead/schema-org@1.8.9" has unmet peer dependency "@unhead/shared@1.8.9".
warning "@nuxtjs/seo > @nuxtjs/sitemap > @nuxt/devtools-ui-kit > @unocss/nuxt > @unocss/vite@0.58.3" has unmet peer dependency "vite@^2.9.0 || ^3.0.0-0 || ^4.0.0 || ^5.0.0-0".
warning "@nuxtjs/seo > @nuxtjs/sitemap > @nuxt/devtools-ui-kit > @unocss/nuxt > @unocss/webpack@0.58.3" has unmet peer dependency "webpack@^4 || ^5".
warning "@nuxtjs/seo > @nuxtjs/sitemap > @nuxt/devtools-ui-kit > unocss > @unocss/postcss@0.58.3" has unmet peer dependency "postcss@^8.4.21".

<--- Last few GCs --->

[81788:00000248C24D3460]   287427 ms: Mark-sweep 4042.0 (4129.2) -> 4034.5 (4138.2) MB, 748.4 / 0.0 ms  (average mu = 0.478, current mu 
= 0.511) allocation failure; scavenge might not succeed
[81788:00000248C24D3460]   289371 ms: Mark-sweep 4050.6 (4138.6) -> 4042.0 (4145.3) MB, 1890.8 / 0.0 ms  (average mu = 0.280, current mu = 0.027) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF79804194F node_api_throw_syntax_error+175855
 2: 00007FF797FC6026 SSL_get_quiet_shutdown+59654
 3: 00007FF797FC7D10 SSL_get_quiet_shutdown+67056
 4: 00007FF798A721F4 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF798A5D582 v8::Isolate::Exit+674
 6: 00007FF7988DF41C v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF7988DC63B v8::internal::Heap::CollectGarbage+3963
 8: 00007FF7988F2873 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
 9: 00007FF7988F311D v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
10: 00007FF7989028E0 v8::internal::Factory::NewFillerObject+816
11: 00007FF7985F3325 v8::internal::DateCache::Weekday+1349
12: 00007FF798B0F751 v8::internal::SetupIsolateDelegate::SetupHeap+558193
13: 00007FF798B2ACA3 v8::internal::SetupIsolateDelegate::SetupHeap+670147
14: 00007FF7191C71BB

**Comment by harlan-zw** [comment]
Seems like a yarn issue if it's crashing when installing the dep? Can you try with pnpm?
