### ISSUE TITLE
[OG Image] Runtime errors in dev tools OG Image preview when SFC has style in `lang=scss`

### ISSUE THREAD

**Issue by ennioVisco** [harlan-zw/nuxt-seo#162]
### Describe the bug

Here is the error I get
![image](https://github.com/harlan-zw/nuxt-seo/assets/740025/8c5fa751-3bd4-4a68-9c3f-5fc56fcd2d7d)

**Comment by harlan-zw** [comment]
Would it be possible to provide a reproduction?

**Comment by dethdkn** [comment]
Hi @harlan-zw, Im also having this issue on my personal webpage

My project uses sass, and OgImage works using version 2.0.0-beta.45
After upgrading to 2.0.0-beta.55 and even switching defineOgImage to defineOgImageComponent I receive the same error as @ennioVisco described
I think it has something to do with having a Footer.vue inside components :o

I tried to create a reproduction, its my first reproduction so, if theres something wrong, please tell me!
Also, message me if theres anything i can help with.
https://stackblitz.com/edit/nuxt-starter-67zxeh?file=components%2FFooter.vue

**Comment by harlan-zw** [comment]
Thanks for the reproduction @dethdkn! It's setup perfectly.

I've pushed up a fix for the bug, there's a wider issue with Nuxt Islands in that it's rendering non-related component styles as part of the render. For example, rendering the home page OG Image also renders the Footer styles... Will need to make an upstream issue.

Available in 3.0.0-rc.28, let me know if you have any further issues.
