### ISSUE TITLE
Generate OG images for dynamic url's

### ISSUE THREAD

**Issue by davies-maina** [harlan-zw/nuxt-seo#164]
### Details

I'm currently working on a Nuxt.js project and facing a challenge with dynamically generating OG images for **dynamic prerendered URLs**. I'm trying to ensure that each page in my application has a unique OG image that reflects its specific content, especially for pages where the content is dynamically loaded.

**Comment by harlan-zw** [comment]
Okay and care to elaborate on the challenge? This should work without issue

**Comment by davies-maina** [comment]
I've rechecked the implementation and it turns out everything is working as expected. It seems I might have overlooked something initially.

P.s
Thank you for your work to the nuxt community!
