### ISSUE TITLE
Ability to sort the sitemap

### ISSUE THREAD

**Issue by misbahansori** [harlan-zw/nuxt-seo#165]
### Clear and concise description of the problem

When generating the sitemap, I noticed that the sitemap is generated based on alphabetical order even when on the API server it's ordered by the last mod. 
Unfortunately, there seems to be no option to customize the sitemap order
This can be a bit cumbersome when you have a lot of pages and you want to check the sitemap to see if everything is ok.

### Suggested solution

Ideally, the sitemap should be ordered by whatever order the pages are on the API server.

**Comment by harlan-zw** [comment]
I need to document it properly but there's a config called `sortEntries` that you can disable the sorting with.
