### ISSUE TITLE
 How to implement dynamic sitemap without relying on third-party external links 

### ISSUE THREAD

**Issue by DokiDoki1103** [harlan-zw/nuxt-seo#166]
### Details

 I don't want to discover URLs through third-party links because I need to maintain another interface. 

 I'm thinking, all requests go through Nitro, so Nitro should record the link of the request so that SEO can be completed? 

<img width="325" alt="图片" src="https://github.com/harlan-zw/nuxt-seo/assets/62740231/6494ff87-41a9-4040-8e18-5a72608a9b1f">

 This type of directory cannot be statically discovered at the beginning, and can only be accessed after the user requests it 

 As long as the user requests it, it will be automatically added to the sitemap, which is much more convenient. How can I configure it 

<img width="412" alt="图片" src="https://github.com/harlan-zw/nuxt-seo/assets/62740231/c43d1e33-52eb-4e23-8dc6-f00a99364c3b">

**Comment by DokiDoki1103** [comment]
<img width="333" alt="图片" src="https://github.com/harlan-zw/nuxt-seo/assets/62740231/80cdf793-128b-49b9-8e26-b83e70a69507">

**Comment by harlan-zw** [comment]
Supporting this isn't something that is going to come to the sitemap module, it is something you can solve in userland though.

You would need to set up a Nitro middleware that would record any new route that's visited, then set up a Nitro plugin that hooks into the sitemap, you would read all entries and insert them.

See https://nuxtseo.com/sitemap/nitro-api/nitro-hooks for an example of how to use that hook.

**Comment by DokiDoki1103** [comment]
<img width="1094" alt="图片" src="https://github.com/harlan-zw/nuxt-seo/assets/62740231/0bc84b6c-b2bd-4c2f-b485-a15633b0b347">

**Comment by harlan-zw** [comment]
Fixed btw ^
