### ISSUE TITLE
Deprecation warnings in @unocss/preset-wind when used with @nuxtjs/seo

### ISSUE THREAD

**Issue by miladshakerdn** [harlan-zw/nuxt-seo#176]
### Details

I install and add `@nuxtjs/seo` to my project, When run `yarn build` will be get warning's like this:
(This occurred only on Windows)

```
(node:19776) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at C:\...\testi\node_modules\@unocss\preset-wind\package.json imported from C:\...\testi\node_modules. Mapping specifiers ending in "/" is no longer supported.

(node:19776) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.mjs" for module request ".//index.mjs" matched to "./*" in the "exports" field module resolution of the package at C:\...\testi\node_modules\@unocss\preset-wind\package.json imported from C:\...\testi\node_modules.
```

Nuxt configuration:

```
# nuxt.config.ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    '@nuxtjs/seo',
  ],
})
```
```
# Package.json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/seo": "^2.0.0-rc.5",
    "nuxt": "^3.9.3",
    "vue": "^3.4.14",
    "vue-router": "^4.2.5"
  },
  "dependencies": {}
}
```

Version's

1.  yarn 1.22.19
2.  node v18.15.0
3.  nuxi 3.5.2

**Comment by harlan-zw** [comment]
Not too sure if there's anything I can do about this, it would be an upstream isssue with UnoCSS

**Comment by michael-hillmann** [comment]
Same for me.

Workaround:
remove @nuxtjs/seo and work with the individual SEO modules

This works for me.

**Comment by leafleaf90** [comment]
Same for me with @nuxtjs/seo. Annoying error messages in the build process, but it still works.

**Comment by plcdnl** [comment]
Same for me. Is there any workaround ?

**Comment by plcdnl** [comment]
solved with new release of unocss https://github.com/unocss/unocss/commit/85827dc5504dc77716b0c5236f308a4e18475c24

**Comment by harlan-zw** [comment]
The latest OG Image module is using the latest unocss with the fix, you can clear your lock file + node_modules and re-install for the fix or wait until the next Nuxt SEO bump.

**Comment by simonmaass** [comment]
i have this error with nuxt 3.16 and nuxt-seo 3.0.0-beta.3

`(node:24572) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at node_modules\@unocss\preset-wind3\package.json imported from node_modules\nuxt-og-image\dist\runtime\server\og-image\context.js. Mapping specifiers ending in "/" is no longer supported.`
