### ISSUE TITLE
[Dev] Update message version

### ISSUE THREAD

**Issue by davidstackio** [harlan-zw/nuxt-seo#179]
### Describe the bug

Not sure if this is in preparation for final release or not, but the version suggested is v1 when running v2 RC in the CLI.

![image](https://github.com/harlan-zw/nuxt-seo/assets/2013388/364d7e2d-e0f5-424a-a896-2cd797041782)

I restarted the dev server twice, but same message.

**Comment by harlan-zw** [comment]
Oh interesting, I guess this was silently failing before as it never came up. The API I use to return the latest version doesn't support the pre-releases so may need to disable this until there's a stable release.

**Comment by davidstackio** [comment]
Yeah, this is the first time I've seen this update message too. Obviously not a big deal, but wanted to file an issue in case it confused some folks who are newer to nuxt-seo and they came here looking for answers.
