### ISSUE TITLE
If I use i18n I need to disable automaticDefaults?

### ISSUE THREAD

**Issue by luca-smartpricing** [harlan-zw/nuxt-seo#193]
### Details

Sorry, but i don't understand the docu. 
[Here](https://www.nuxtseo.com/nuxt-seo/guides/default-meta#i18n) you say: 
> If you're using the @nuxtjs/i18n module, then this is automatically set for you.

What does i18n do? Set `currentLocale` and `defaultLocale` or add all the metas that would be added with `automaticDefaults: true`?
I think it's the second option because I see all the og:tags duplicated.
So if I use i18n I must necessarily disable `automaticDefaults`
Can you clarify this point for me?
Thanks and great work!

**Comment by harlan-zw** [comment]
No og tags should be duplicated, you can try out 2.0.0-rc.9 and let me know if it works any better. 

Otherwise if you can provide a reproduction it would help me debug.

**Comment by harlan-zw** [comment]
Some improvements have been made in 2.0.0-rc.17, however, I18n is not fully reactive, I made an issue here to track: https://github.com/harlan-zw/nuxt-seo/issues/283

You may need to omit the i18n useLocaleHead function
