### ISSUE TITLE
Site Not Found

### ISSUE THREAD

**Issue by lnbiuc** [harlan-zw/nuxt-seo#198]
### Details

[https://nuxtseo.com/](https://nuxtseo.com/) site not found

![image](https://github.com/harlan-zw/nuxt-seo/assets/85148161/06d1e57f-4bc4-406b-9072-8c62011e6442)

**Comment by harlan-zw** [comment]
I recently migrated the site to Vercel, seems like your DNS is still using the Netlify host. Maybe you can try clearing your cache?

**Comment by lnbiuc** [comment]
Okay, I understand. Thank you for your reply.
