### ISSUE TITLE
Could not load raw:@iconify-json

### ISSUE THREAD

**Issue by roboriba** [harlan-zw/nuxt-seo#203]
### Describe the bug

The problem is loading the module from node modules, for some reason it uses project/@iconify-json and not project/node_modules/@iconify-json. I don't know why this is happening I have tested three versions of node: 20.11.1, 18.17.0 and 16.20.1 it doesn't work on any of them, I have also changed NPM versions and again nothing.

`Could not load raw:@iconify-json/noto/chars.json (imported by node_modules/nuxt-og-image/dist/runtime/nitro/og-image/satori/transforms/emojis.mjs): ENOENT: no such file or directory, open 'C:\Users\user\Desktop\projects\test\@iconify-json\noto\chars.json'`

I also tried the nuxt-og-image module, but still the same problem.

I know that the problem is only related to one module @nuxtjs/seo. But I'm putting the bug report here because @nuxtjs/seo seems like a great idea. And I'm very sorry that I can't use it at the moment. 

Otherwise the hotfix is to disable the module in the nuxt config.

### System / Nuxt Info

```Shell
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.2
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      devtools, modules, css, vue, sitemap, site, runtimeConfig, app
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @nuxtjs/seo@2.0.0-rc.8
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
Can you try delete your lock file + node_modules and re-install? I believe this was a Nitro regression

**Comment by roboriba** [comment]
I've done it about 3 times.

**Comment by harlan-zw** [comment]
I've pushed up a workaround for the nitro regression in rc.43 of the og image module, you can update by deleting lock file + node_modules and re-installing.
