### ISSUE TITLE
I'm encountering an unexpected issue when combining Nuxt and Nuxt Schema Org.

### ISSUE THREAD

**Issue by kng-caoxuanson** [harlan-zw/nuxt-seo#204]
### Details

I'm coding with the following dependencies:

`"nuxt": "^3.10.2",
"nuxt-schema-org": "^3.3.4"
`

However, when integrated, the URL automatically adds a trailing slash at the end of the page in the schema. Even though I have configured trailingSlash: false in the nuxt.config.ts file.

I'm trying to achieve the following result:

Current: https://kimkhicholon.com/danh-muc/#webpage
Desired: https://kimkhicholon.com/danh-muc#webpage

<img width="734" alt="Screenshot 2024-03-11 at 8 53 52 PM" src="https://github.com/harlan-zw/nuxt-seo/assets/92279524/013a4092-2564-4d8f-92c1-4f51add82649">

I appreciate any guidance on how to achieve this. Thank you.

**Comment by harlan-zw** [comment]
Hmm strange, are you using base URLs by any chance :thinking: ? A reproduction would help me solve it faster for you, you can use https://stackblitz.com/edit/github-v9xq4g-nzfy4x?file=nuxt.config.ts as a starter

**Comment by kng-caoxuanson** [comment]
> Hmm strange, are you using base URLs by any chance 🤔 ? A reproduction would help me solve it faster for you, you can use https://stackblitz.com/edit/github-v9xq4g-nzfy4x?file=nuxt.config.ts as a starter

In your example
I see it still has /#website

<img width="914" alt="Screenshot 2024-03-12 at 4 31 56 PM" src="https://github.com/harlan-zw/nuxt-seo/assets/92279524/2e2c4c8d-2670-49ad-9443-a8d0e1040c02">

**Comment by harlan-zw** [comment]
The trailing slash on the root domain is expected, either is fine but it's better practice to include it as this is how browsers will generally resolve it

**Comment by Duzbee** [comment]
The trailing slash triggers a "pages with redirect" in my Google Search Console for all my pages. It must be removed when trailingSlashes option is set to default. Also the schema-org:meta hook only triggers on the client side and the meta object is completly empty.

**Comment by harlan-zw** [comment]
The trailing slash on the root path won't trigger this. Can you please provide a reproduction if you have a separate issue?
