### ISSUE TITLE
How to add prefix for the sitemap.xml path

### ISSUE THREAD

**Issue by anjali89r** [harlan-zw/nuxt-seo#207]
### Details

I have a blogs project that is going to separate from the existing website and want to generate the sitemap.xml for this blogs project as this _`example.com/blogs/sitemap.xml`_
Is this possible with the sitemap module now ?

**Comment by harlan-zw** [comment]
Hi, it sounds like you should be using the Nuxt [baseURL ](https://nuxt.com/docs/api/nuxt-config#baseurl) option?

```ts
export default defineNuxtConfig({
  app: {
    baseURL: '/blogs'
  }
})
```

The sitemap module should emit the correct paths from there.
