### ISSUE TITLE
Favicon with baseURL

### ISSUE THREAD

**Issue by dethdkn** [harlan-zw/nuxt-seo#219]
### Details

Hi I've built a webpage with Nuxt and NuxtSeo, but Im using baseURL in nuxt.config.ts
```
app: {
	baseURL: '/example',
},
```
So instead of localhost:3000, my page is at localhost:3000/example
But the favicon in the generate html still resolves to
`<link rel="icon" href="/favicon.ico" sizes="any">`
It should be
`<link rel="icon" href="/example/favicon.ico" sizes="any">`
So it could use the public folder of my project... right?

Am I missing something and being dumb? haha
Or is there a way to manually define the favicon path?

**Comment by harlan-zw** [comment]
Thanks for the issue, this was a bug in the nxut-seo-experiments module. I've pushed up a fix in nuxt-seo-experiments@4.0.0-rc.6.

If you clear your lock file + node_modules and re-install it should use it, otherwise you can manually pin it.
