### ISSUE TITLE
i18n integration

### ISSUE THREAD

**Issue by zonistefano** [harlan-zw/nuxt-seo#223]
### Describe the bug

The integration with i18n is not working as expected. When switching the locale as described by the nuxtjs/i18n documentation, the  Default Meta are not updated accordingly. The affected properties are: html lang="<locale>", og:locale, og:site_name, %siteName from the page title.
Those properties are updated only when a page refresh is manually triggered from the browser button.

### Reproduction

https://github.com/zonistefano/nuxtseo

### System / Nuxt Info

```Shell
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  bun@1.0.29
- Builder:          -
- User Config:      devtools, site, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.3.0, @nuxtjs/seo@2.0.0-rc.10
- Build Modules:    -
```

**Comment by ulysse-lacour** [comment]
Same issue for me (with no_prefix)

**Comment by harlan-zw** [comment]
Hey, thanks for this issue and reproduction. This is slightly improved in RC 17 but we still don't have full reactivity. 

I've created a new issue to track that here: https://github.com/harlan-zw/nuxt-seo/issues/283
