### ISSUE TITLE
Multisitemaps and global sources

### ISSUE THREAD

**Issue by plexus77** [harlan-zw/nuxt-seo#236]
### Details

I have some global sources set sitemap.sources and the items in these sources specify the sitemap they belong to using the `_sitemap` attribute.  Using the documentation in particular the example [shown here](https://nuxtseo.com/sitemap/guides/multi-sitemaps#extending-app-sources) and below

```
    ...
    sitemaps: {
      pages: {
        includeAppSources: true,
        exclude: ['/**']
        // ...
      },
    },
```

I would expect the app source pages and the global source pages to turn up, however only the app source turns up in the sitemap.  

After looking at the debug information I noticed that the sitemap.sources data ends up in a globalSources object... So I made up an attribute `includeGlobalSources: true` and lo and behold it works... Is this some strange bug or simply an undocumented feature.

**Comment by harlan-zw** [comment]
Hi, this is the expected behaviour. I've pushed up some documentation fixes around this.
