### ISSUE TITLE
lang and icon reported missing if set in `nuxt.config.ts`

### ISSUE THREAD

**Issue by emavitta** [harlan-zw/nuxt-seo#245]
### Describe the bug

If i set the lang and the icon in the `nuxt.config.ts`file, it doesn't get discovered in devtools and is reported as missing.

<img width="926" alt="image" src="https://github.com/harlan-zw/nuxt-seo/assets/57635138/08a1e307-b81f-4339-8c37-fee970ee9df2">

In this example i just set the lang.

I don't know if has something to do with #147 or #274

### Reproduction

https://stackblitz.com/edit/nuxt-starter-monleb?file=layout%2Fdefault.vue,app.vue,pages%2Findex.vue,nuxt.config.ts

**Comment by harlan-zw** [comment]
Hi, this is a bug in the Nuxt DevTools. There is a similar issue here https://github.com/nuxt/devtools/issues/636

I'll close this in favour of that as there's nothing I can do from this module.
