### ISSUE TITLE
url pattern matching doesnt work for matching partial paths

### ISSUE THREAD

**Issue by jpengelbrecht** [harlan-zw/nuxt-seo#247]
### Describe the bug

using the docs specified here.  
https://nuxtseo.com/sitemap/guides/route-rules

using route rules you can do 
/help/** to not index anything inside of help.  

however partial matching doesn't work.  
so for instance
/help/10* this should not index anything inside help starting with 10.  

this is useful for slug vs ID paths. 

### System / Nuxt Info

```Shell
- Operating System: Darwin
- Node Version:     v18.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      modules, site, linkChecker, css, turnstile, robots, app, routeRules, typescript, sourcemap, devServer, devtools, htmlValidator, image, ogImage, runtimeConfig, schemaOrg, nitro, experimental, appConfig, ignore, hooks, vite
- Runtime Modules:  @nuxtjs/algolia@1.10.1, @nuxt/devtools@1.3.2, @pinia/nuxt@0.5.1, @nuxt/content@2.11.0,
```

**Comment by harlan-zw** [comment]
Hi, thanks for the issue.

Unfortunately, all path matching is handled by [radix3](https://github.com/unjs/radix3) which does not support these features.

I'd suggest using [hooks](https://nuxtseo.com/sitemap/nitro-api/nitro-hooks) if you need more complex logic.
