### ISSUE TITLE
LD+JSON does not update when running in production

### ISSUE THREAD

**Issue by marcobax** [harlan-zw/nuxt-seo#249]
### Describe the bug

When using Nuxt SEO + Nuxt schema.org in production, the schema.org JSON+LD does not seem to update when using <NuxtLink>

[Example code on Stackblitz](https://stackblitz.com/edit/nuxt-starter-wajnwe?file=pages%2Findex.vue)

Run `npm run build`, then `node .output/server/index.mjs` to see the issue. Navigate from the homepage to the recipe, and check out the generated schema.org data in devTools. This value will not be updated when navigating to the blog, and vice versa.

This problem does not occur when running `npm run dev` or when refreshing the page manually.

**Comment by harlan-zw** [comment]
Hi, thanks for the reproduction.

Please see [Production Static data](https://nuxtseo.com/schema-org/getting-started/how-it-works#production-static-data).
