### ISSUE TITLE
Docs break when deploying new versions

### ISSUE THREAD

**Issue by harlan-zw** [harlan-zw/nuxt-seo#257]
### Describe the bug

![image](https://github.com/harlan-zw/nuxt-seo/assets/5326365/de974b82-ea94-49be-8b18-54491233b0a8)

**Comment by jrutila** [comment]
Just reporting this error that I am getting when upgraded from 2.0.0-rc.10 to 2.0.0-rc.11. Might be related, or not.

> overlay.mjs:2 Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@vue/devtools-core/dist/index.js?v=73c5dc5d' does not provide an export named 'initAppSeparateWindow' (at overlay.mjs:2:10)

**Comment by jrutila** [comment]
That error prevents using `nuxt dev` as it blocks the whole load.

**Comment by harlan-zw** [comment]
> Just reporting this error that I am getting when upgraded from 2.0.0-rc.10 to 2.0.0-rc.11. Might be related, or not.
> 
> > overlay.mjs:2 Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@vue/devtools-core/dist/index.js?v=73c5dc5d' does not provide an export named 'initAppSeparateWindow' (at overlay.mjs:2:10)

Looks like a bug in the latest @vue/devtools, maybe consider locking to an older version or try `nuxi upgrade --force`

**Comment by harlan-zw** [comment]
The core issue was fixed, it was relating to some dodgy useScript code.
