### ISSUE TITLE
disable alternative URLs from useHead, SEO plugin?

### ISSUE THREAD

**Issue by pixelpaulaus** [harlan-zw/nuxt-seo#259]
### Details

I have the SEO plugin that adds alternative URLs to the pages meta via useHead, I am not using the autoI18n plugin.
I noticed that the alternative URLs are being added to the sitemap.
I want these disabled, so I tried adding:
`autoI18n: false` to the sitemap config, but they are still being added.

How can I disable the alternative URLs in the sitemap that are getting added from the useHead SEO plugin?

**Comment by harlan-zw** [comment]
Hey, can you provide a [reproduction](https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue)? This module and all child modules do not add any alternative tags using `useHead`.

`autoI18n: false` should disable any alternatives

**Comment by pixelpaulaus** [comment]
`autoI18n: false` doesnt disable the alternatives in this case. Also Nuxt I18n isn't even being used at all.

We are manually adding the hreflag to via useHead() like soo....

```
{rel: 'alternate', href: 'https://www.domain.ca' + route.path, hreflang: 'en-CA'},
{rel: 'alternate', href: 'https://www.domain.eu' + route.path, hreflang: 'en-BE'},
```

that is where it is getting them from, but there is no way to tell it NOT to include them in the sitemap output.

**Comment by pixelpaulaus** [comment]
> Can you provide a reproduction?

not really sorry. But there is nothing unusual/custom about how we use it.

**Comment by harlan-zw** [comment]
Okay but I can't help without one so I'll close this until there's one available

**Comment by pixelpaulaus** [comment]
the bug it still there, so you should keep it open until it is fixed.

**Comment by harlan-zw** [comment]
It's not clear how to reproduce the big so I can't fix it
