### ISSUE TITLE
Type unkown from Plugin after enabling @nuxt/seo

### ISSUE THREAD

**Issue by mod08** [harlan-zw/nuxt-seo#260]
### Describe the bug

As soon as I add the @nuxtjs/seo Module to an empty Nuxt Project the Type of my provided Plugin Variable becomes unkown.

Since i wasn't able to reliable reproduce this in Stackblitz i created this short video.

![nuxt-seo-type-unkown](https://github.com/harlan-zw/nuxt-seo/assets/25512687/a860b89a-3d8d-41fc-9951-8c3cdb11e76b)

### System / Nuxt Info

* Nuxt 3.12.2 (Starter Template)

**Comment by asokawotulo** [comment]
I'm experiencing the same issue. 
I did a bit of digging and it looks like when Nuxt is trying to inject the plugins, the following plugin files do not have a default return value

- nuxt-seo-experiments/dist/runtime/nuxt/plugins/1.absoluteImageUrls.server
- nuxt-seo-experiments/dist/runtime/nuxt/plugins/0.routeRules.server
- nuxt-seo-experiments/dist/runtime/nuxt/plugins/siteConfig
- nuxt-seo-experiments/dist/runtime/nuxt/plugins/inferSeoMetaPlugin
- nuxt-simple-robots/dist/runtime/nuxt/plugins/robot-meta.server
- nuxt-site-config/dist/runtime/nuxt/plugins/i18n.server
- nuxt-site-config/dist/runtime/nuxt/plugins/0.siteConfig

My temporary workaround is to comment those lines in `.nuxt/types/plugins.d.ts`

**Comment by mhelbich** [comment]
Can confirm this is happening to me too.

Some info:
Nuxt version 3.12.3 (although it also happened with 3.12.2 as mentioned above)
@nuxtjs/seo: ^2.0.0-rc.11

With the module enabled:
![image](https://github.com/harlan-zw/nuxt-seo/assets/54327863/174ef793-d0f3-4c61-b912-d79e947dc496)
![image](https://github.com/harlan-zw/nuxt-seo/assets/54327863/66fa22da-970b-4681-a910-44a05e91f1d6)

With the module disabled:
![image](https://github.com/harlan-zw/nuxt-seo/assets/54327863/ca74ad6e-40cc-449a-935e-3b97535c9a71)
![image](https://github.com/harlan-zw/nuxt-seo/assets/54327863/abd6ab17-3546-4e10-af05-c64f7db68a33)


And I can also confirm that commenting out the plugin declarations that @asokawotulo mentioned resolves the issue.
![image](https://github.com/harlan-zw/nuxt-seo/assets/54327863/c57cdb94-7705-47bb-924f-fce00c4a5bb2)
($caFetch is no longer `unknown` with this)

I was browsing through https://github.com/nuxt/nuxt/issues/24885 and https://github.com/nuxt/module-builder/issues/215 as well as some mentions of the "plugin type unknown" on the Nuxt Discord, but wasn't able to find anything else to get it to work.

**Comment by hmd-ali** [comment]
Not sure if this belongs in this category, but the `app` property in `defineNuxtConfig` is typed `any` whenever the `@nuxtjs/seo` module is enabled 
![image](https://github.com/harlan-zw/nuxt-seo/assets/83613364/647acc58-e686-46b7-8256-aa9bab676e62)
![image](https://github.com/harlan-zw/nuxt-seo/assets/83613364/90fbcfe2-6cd8-4970-82e3-44ad2a9f8629)

**Comment by harlan-zw** [comment]
You can delete your lock file + node_modules and then re-install the dependencies, it will automatically update any sub-dependencies using caret version constraints.

**Comment by harlan-zw** [comment]
Okay 2.0.0-rc.12 was pushed out which should fix this.

> Not sure if this belongs in this category, but the `app` property in `defineNuxtConfig` is typed `any` whenever the `@nuxtjs/seo` module is enabled

Would you mind making a new issue for this please :pray:
