### ISSUE TITLE
Dinamically set SiteConfig for different locales with i18n

### ISSUE THREAD

**Issue by T-Mike** [harlan-zw/nuxt-seo#262]
### Details

I couldn't find a way to dynamically set SiteConfig for different locales. I need to fetch the infos from a CMS.
The documentation explains :
1. [how to set SiteConfig statically via files](https://nuxtseo.com/site-config/integrations/i18n) but not dynamically
2. [How to do it via plugin or middleware](https://nuxtseo.com/site-config/guides/runtime-site-config) but not for all locales

Is it possible for now and what strategy would you use ?
In either case, I think it would be great to update the docs to mention it.

Thanks a ton for this module! 🫶

**Comment by harlan-zw** [comment]
Hi, I'd suggest using a Nitro plugin where you fetch the data on init, then add a hook for any request where you update the site config.

The code sample I have in 2 is exactly what I'm talking about.

```ts
export default defineNitroPlugin(async (nitroApp) => {
  // fetch the infos from a CM
  const infos = await $fetch('/db/site-config', {
    params: { env: import.meta.env.NUXT_SITE_ENV },
  })
  // init the site config
  nitroApp.hooks.hook('site-config:init', ({ event, siteConfig }) => {
    // presumably info has mapping of all the URLs and data
    const siteData = infos.filter(i => getRequestUrl(event) === i.host)
    siteConfig.push(siteData)
  })
})
```
