### ISSUE TITLE
when the `titleTemplate` of `useHead()` is a function and being used to generate the value of `og:title`, its first param will be the last part of route path instead of the `title` of `useHead()`

### ISSUE THREAD

**Issue by n0099** [harlan-zw/nuxt-seo#263]
### Describe the bug

As title.
![image](https://github.com/harlan-zw/nuxt-seo/assets/13030387/4618ba6d-98f6-4a90-b960-9344bf8dc211)
![image](https://github.com/harlan-zw/nuxt-seo/assets/13030387/a16e5aec-30ed-4427-878d-a2367e80f7de)

### Reproduction

https://stackblitz.com/edit/nuxt-starter-moa1dd

**Comment by harlan-zw** [comment]
I think this may be related to https://github.com/harlan-zw/nuxt-seo/issues/137 which I've pushed up a fix for in the latest RC.
