### ISSUE TITLE
defineOgImageComponent is undefined in component testing with @nuxt/test-utils

### ISSUE THREAD

**Issue by adamdehaven** [harlan-zw/nuxt-seo#265]
### Describe the bug

When mounting a component with `mountSuspended` or `renderSuspended` via `@nuxt/test-utils`, when the exports are compiled for the tests, `defineOgImageComponent` (and `defineOgImage`, etc.) composable is not available for import and throws an error:

```sh
ReferenceError: defineOgImageComponent is not defined
```

When running `nuxt prepare` manually, the exports exist; however, when testing with `@nuxt/test-utils` the composables do not seem to be available/resolve correctly.

### System / Nuxt Info

```Shell
- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.3.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
This would be an upstream issue in https://github.com/nuxt/test-utils, not sure there's anything I can do within the module to help.

The workaround your using looks good.

**Comment by adamdehaven** [comment]
I'm wondering if there's an underlying issue in the test-utils repo whereby the equivalent of the `prepare` script is either different, or doesn't accurately generate all necessary types for installed modules 🤔  

Unsure of where to look over there

**Comment by harlan-zw** [comment]
I'll need to close this for now because there aren't any more next steps I can take.

The workaround is good because nuxt-og-image will automatically mock composable functions when the module is disabled so it's actually working perfectly.

Ideally `@nuxt/test-utils` has a solution for this in the future though.

**Comment by adamdehaven** [comment]
Yep the composables are mocked so no errors. Only suggestion would be a note in the docs somewhere

**Comment by kieron** [comment]
Any idea what to do if im getting this but not using vitest or @nuxt/test-utils?
