### ISSUE TITLE
Website / Docs are down

### ISSUE THREAD

**Issue by MickL** [harlan-zw/nuxt-seo#269]
### Describe the bug

Most parts of the website are down / not working. Often they show an error from Vercel that the function crashed, e.g.:

https://nuxtseo.com/sitemap/getting-started/installation
https://nuxtseo.com/schema-org/getting-started/installation

**Comment by harlan-zw** [comment]
Thanks, seems like something strange related to upgrading `shiki` :thinking: 

> Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/shiki/dist/core.mjs' imported from /var/task/index.mjs

**Comment by BobbieGoede** [comment]
I'm getting error 500 (500 This page is temporarily unavailable.) pages when directly navigating to doc pages except for the homepage. The pages work fine when navigating from the homepage to these pages, reloading also shows an error 500.

A few random pages I tried
- https://nuxtseo.com/robots/getting-started/installation
- https://nuxtseo.com/og-image/guides/non-english-locales
- https://nuxtseo.com/og-image/api/define-og-image

**Comment by harlan-zw** [comment]
Seems like an issue with Nuxt 3.12.4 :face_with_diagonal_mouth: 

> [nuxt] [request error] [unhandled] [500] Cannot find module '/var/task/node_modules/vue/server-renderer/index.mjs' imported from /var/task/chunks/routes/renderer.mjs

Have pinned to 3.12.3 for the time being to fix
