### ISSUE TITLE
Nested Sitemaps

### ISSUE THREAD

**Issue by SamanFattahiDev** [harlan-zw/nuxt-seo#277]
### Details

**Describe The Bug**

i have a ,multi language website and i need a sitemap schema like this

1. ar_sitemap
 2.products_sitemap
 3.categories_sitemap 

1. en_sitemap
 2.products_sitemap
 3.categories_sitemap 

the issue is when im trying to create nested configuration as explained in documentation, i came up with this configuration
`  sitemap: {
                    sitemaps:{
                     en:{
                         products:{
                              resources:['/api/__sitemap__/urls/en/products']
}   ,
        categories:{
                              resources:['/api/__sitemap__/urls/en/categories']
}   
}
}
            },
        `

problem is that in the sitemap preview, it renders first level like en_sitemap.xml. but when i go deeper to the next level there is nothing like products_sitemap.xml and categories_sitemap.xml. i wanted to know that is there anything like this implemented in the package? or am i doing something wrong in the configuration?

**Reproduction**

-

**System / Nuxt Info**

`- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, app, css, link, postcss, modules, i18n, pwa, runtimeConfig, experimental, site, sitemap
- Runtime Modules:  @nuxtjs/i18n@8.1.0, @pinia/nuxt@0.5.1, @nuxt/image@1.3.0, nuxt-swiper@1.2.2, @pinia-plugin-persistedstate/nuxt@1.2.0, @vite-pwa/nuxt@0.4.0, @nuxtjs/sitemap@5.3.2, nuxt-simple-robots@4.0.0-rc.19, nuxt-schema
-org@3.3.8
- Build Modules:    -
`

**Comment by harlan-zw** [comment]
The sitemap protocol [doesn't support multiple index sitemaps](https://webmasters.stackexchange.com/questions/18243/can-a-sitemap-index-contain-other-sitemap-indexes), you should use a flat structure.
