### ISSUE TITLE
Enable automatic chunking when customizing a multisitemap

### ISSUE THREAD

**Issue by censujiang** [harlan-zw/nuxt-seo#281]
### Clear and concise description of the problem

When I have a site with a large number of links, it is more user-friendly to group the links into categories and automatically chunk them.

For example, enabling sitemapsChunk:true in the code is a flag to turn on this feature

```ts
  sitemap: {
    sitemaps: {
      urls:{
        sources: [
          `/api/__sitemap__/urls`,
         sitemapsChunk:true
        ],
      }
    },
```

Then, assuming there are 10,000 links, the sitemap will be divided into urls-0-sitemap.xml, urls-1-sitemap.xml and other pages

### Suggested solution

@nuxtjs/sitemap

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. I'm tracking this feature here: https://github.com/nuxt-modules/sitemap/issues/265

**Comment by censujiang** [comment]
> Hi, thanks for the issue. I'm tracking this feature here: [nuxt-modules/sitemap#265](https://github.com/nuxt-modules/sitemap/issues/265)

ok, thank you
