### ISSUE TITLE
Website icons 

### ISSUE THREAD

**Issue by lwildermuth** [harlan-zw/nuxt-seo#284]
The website icons don't seem to load. If I can be of any help let me know
[https://nuxtseo.com/robots/getting-started/installation](https://nuxtseo.com/robots/getting-started/installation)
<img width="1325" alt="Screenshot 2024-08-07 at 7 59 37 pm" src="https://github.com/user-attachments/assets/a132eaf7-57f5-49a5-bf02-fd6144830727">

**Comment by harlan-zw** [comment]
Thanks, looks like Nuxt UI had a breaking change in a minor. Fixed now
