### ISSUE TITLE
Error on Update to rc.17 Version - "Cannot read properties of undefined (reading 'locale')"

### ISSUE THREAD

**Issue by hoythan** [harlan-zw/nuxt-seo#286]
### Describe the bug

**Description**
After updating to version rc.17 of @nuxtjs/seo, our website has crashed with the following error:
```
500
Cannot read properties of undefined (reading 'locale')
```
**Error Details**
The error seems to originate from the following piece of code:

```
const Kd = rt({
    name: "nuxt-seo:defaults",
    env: {
        islands: !1
    },
    dependsOn: [],
    setup(t) {
        const e = yt(t.$i18n.locale.value);
        t.hook("i18n:localeSwitched", ({newLocale: n})=>{
            e.value = n
        }),
        Gd({
            locale: e
        })
    }
})
```

**Steps to Reproduce**
Update @nuxtjs/seo to version rc.17.
Deploy or run the Nuxt.js application.
The application crashes and displays the above error.

**Expected Behavior**
The application should run without crashing and handle the locale property correctly.

**Additional Context**

- The previous version (rc.1 7) worked without any issues.
- The issue seems to be related to the handling of the $i18n.locale.value.

Please investigate and provide a fix as soon as possible. Thank you for your attention to this matter.

<img width="1900" alt="image" src="https://github.com/user-attachments/assets/6246f78b-aefe-4848-8b84-33a52e2c811f">

**Comment by harlan-zw** [comment]
Hi, sorry about this.

Could you please try  RC 18?
