### ISSUE TITLE
[Sitemap] how to implement i18n and content?

### ISSUE THREAD

**Issue by farhodhojiev** [harlan-zw/nuxt-seo#287]
### Details

Sitemap generating normally `sitemap_index.xml` with two split files: `en-sitemap.xml` and `tg-sitemap.xml` with current pages.
Also i use content for documentation in 2 languages.
Contents in 2 folders `content/doc/en` and `content/doc/tg`
And need to add all `content/doc/en` content files to `en-sitemap.xml` and all `content/doc/tg` content files to `tg-sitemap.xml`.

Thank you in advance.

**Comment by farhodhojiev** [comment]
Sorry for late answer, but does not work.
I have list of contents in `devtools`, but not in `sitemap`.
![image](https://github.com/user-attachments/assets/ba55b0d1-c315-479d-a572-dbf1a91653a9)

**Comment by ptdev** [comment]
Hi,

Well, you appear to have it similar to our setup, we get this on our devtools:

![image](https://github.com/user-attachments/assets/f45162ac-a21c-47bc-97fd-d464585a2689)

Which looks pretty much the same. But in our case the url's get correctly placed into each language sitemap.

The only difference I can see from your post is that you have your content inside a "doc" folder, like "content/doc/[lang]".

We have our language folders directly inside the content folder, so "content/[lang]/folderXYZ".

Not sure if that makes any difference. We just use it like that as it was the recommended approach when using nuxt-content with nuxt-i18n.

Other than that, can't really see what could be wrong but feel free to post more details or questions.

Cheers

**Comment by farhodhojiev** [comment]
I tried different ways, but it doesn’t work. Maybe it’s necessary to explicitly indicate which language to add?
```js
return {
      loc: url,
      lastmod: new Date(),
      sitemap: 'en', // ???
}
```

**Comment by harlan-zw** [comment]
You can specify which sitemap a path ends up in by using the `_sitemap` key. The module is not fully tested with Nuxt I18n and Nuxt Content combined but there is likely a workaround as @ptdev has tried to assist with.

Please provide a minimal reproduction and I can help further, you can use the i18n starter https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue

**Comment by farhodhojiev** [comment]
Sorry for bothering you, it was my mistake, there was a problem with include and exclude.
Now work perfect.
