### ISSUE TITLE
Docs are broken — icons display as text, making for cluttered interface

### ISSUE THREAD

**Issue by Krislunde** [harlan-zw/nuxt-seo#289]
### Describe the bug

All icons currently on the docs are broken and displayed as text, making for a cluttered interface and bad user experience.

<img width="2012" alt="Screenshot 2024-08-08 at 00 18 36" src="https://github.com/user-attachments/assets/2b2b9fb5-5234-4671-8073-2692b0bc26d3">
<img width="1416" alt="Screenshot 2024-08-08 at 00 18 58" src="https://github.com/user-attachments/assets/2187ee65-417d-44a0-91f9-2168f0f098a7">
<img width="1450" alt="Screenshot 2024-08-08 at 00 19 08" src="https://github.com/user-attachments/assets/02e1f196-23e4-4fbf-ac53-08748a4b9bd6">

### Reproduction

Just visit the docs — https://nuxtseo.com

### System / Nuxt Info

```Shell
N/A
```

**Comment by harlan-zw** [comment]
Thanks, looks like Nuxt UI had a breaking change in a minor. Fixed now
