### ISSUE TITLE
Recommended starting point and Module/version fatigue

### ISSUE THREAD

**Issue by genu** [harlan-zw/nuxt-seo#291]
### Details

Hey @harlan-zw, thanks for your work on this. I really appreciate your dedication to the project.

I'd like to integrate this module in a new project, but I'm not exactly sure about where to start. Its not clear if I should install the  main module RC `@nuxtjs/seo`. Does that include all the other modules? Does it include the latest of those modules (betas/rc, etc)?

What should I be installing right now if I'm staring a new nuxt 3/4 project?

**Comment by genu** [comment]
Thanks @harlan-zw.

If if starting out now, I would install `pnpm i -D @nuxtjs/seo`?

**Comment by harlan-zw** [comment]
Yup 👍

**Comment by genu** [comment]
Great thx! 🙏
