### ISSUE TITLE
Sitemap.xml Generation Error in nuxt-seo v2.0.0-rc.18

### ISSUE THREAD

**Issue by hoythan** [harlan-zw/nuxt-seo#296]
### Describe the bug

In version 2.0.0-rc.18 of nuxt-seo, the sitemap.xml is generated incorrectly. This issue can be consistently reproduced in the production environment.

The generated URLs have the following incorrect format, and the content is empty:

/__sitemap__/en.xml
/__sitemap__/zh-CN.xml
/__sitemap__/zh-TW.xml
In version 2.0.0-rc.16, the generated URLs were in the correct format:

/en-sitemap.xml
/zh-CN-sitemap.xml
/zh-TW-sitemap.xml

**Comment by harlan-zw** [comment]
Yes, the release notes this as a slightly breaking change, see https://github.com/nuxt-modules/sitemap/pull/320.

So the new path is correct, if they're empty can you provide a minimal reproduction as this sounds like a bug

**Comment by harlan-zw** [comment]
Seems like there was a bug in the latest robots module, if you clear your lock file and update your dependencies it should fix the empty issue.
