### ISSUE TITLE
Nuxt Sitemap does not include the images even though the Nuxt content pages contain many images.

### ISSUE THREAD

**Issue by Aravinda93** [harlan-zw/nuxt-seo#298]
I am developing a `Nuxt content` website for documentation purposes and using the `Nuxt Sitemap` in it. 

I have created a similar repo as my original project on [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fpages%2Fdocs%2F%5B...slug%5D.vue%3A15%2C1). Can someone please have a look and provide some solutions on the automatic generation of sitemap for images in the Nuxt Content project?

I am adding the `sitemap` information to my `/content/docs` with all the `markdown` or .md files such as:

`/content/docs/introduction/index.md`:

```
---
title: "Introduction"
description: My Introduction to content website
sitemap:
  loc: /docs/introduction
  lastmod: 2024-08-30
  changefreq: quaterly
  priority: 0.9
___
```

I can generate the `sitemap.xml` file during the `npm run generate` but this generates the `url` only for the routes that are present in `/content/docs` where I have added the `sitemap` information to my `index.md` files such as this in:

```
<url>
    <loc>https://example.io/docs/introduction</loc>
    <lastmod>2024-08-30</lastmod>
    <changefreq>quaterly</changefreq>
    <priority>0.9</priority>
    <xhtml:link rel="alternate" href="https://example.io/docs/introduction" hreflang="x-default" />
    <xhtml:link rel="alternate" href="https://example.io/docs/introduction" hreflang="en" />
</url>
```

I have many images within this `index.md` file but these images are for some reason not included in the `sitemap.xml` file. I don't want to specify each image in my all `.md` files rather want a dynamic approach where `Nuxt Content/Sitemap` can automatically scan and include all images in my `/content/docs` so it's all included in `sitemap.xml` file.

I added the following:
```
sitemap: {   
  urls: [
    {
      loc: '/docs',
      images: [
        {
          loc: 'https://example.io/docs/introduction/image1.png',
          caption: 'My image caption',
          geoLocation: 'My image geo location',
          title: 'My image title',
          license: 'My image license',
        }
      ]
    }
  ]
},
```

This will add only the specified image here to my `sitemap.xml` file. However, I have a lot of images in different .md files within my `Nuxt content /content/docs`. How to include all dynamically and directly without specifying each of them here in `nuxt.config.js` file?

1. I added the following by looking into the [Nuxt Content Documentation](https://nuxtseo.com/sitemap/integrations/content)

```
//To support and display the .md files from /content using @nuxt/content
content: {
  documentDriven: true,
  sitemap: true,
  //To get the reading time for each .md file in /content
  markdown: {
    remarkPlugins: ["remark-reading-time"],
  },
  //To build the sitemap for SEO automatically using @nuxt/sitemap
  strictNuxtContentPaths: true
},

sitemap: {
  sources: [
    '/api/__sitemap__/urls'
  ]
},
```

And a file in `/server/api/__sitemap__/urls.ts` but this also does not make any difference and I do not get my images or videos in sitemap.xml file:
```
import { defineEventHandler } from 'h3'
import type { ParsedContent } from '@nuxt/content/dist/runtime/types'
import { serverQueryContent } from '#content/server'
import { asSitemapUrl, defineSitemapEventHandler } from '#imports'

export default defineSitemapEventHandler(async (e) => {
  const contentList = (await serverQueryContent(e).find()) as ParsedContent[]
  return contentList
    .filter(c => c._path.startsWith('docs'))
    .map((c) => {
      return asSitemapUrl({
        loc: `/blog/${c._path.replace('docs', '')}`,
        lastmod: updatedAt
      })
    })
})
```

2. As per mentioned in the [Nuxt SiteMap Automatic Image Discovery](https://nuxtseo.com/sitemap/guides/images-videos#automatic-image-discovery) i wrapped my `layouts/default.vue` with `<main>` something like this:

```
<!-- Page Content -->
<div class="w-full flex flex-col flex-grow">
  <main>
    <slot />
  </main>
</div>
```

Previously I was just using the ` <slot />`. Even after adding the `<main>` when I generate the `.output` I don't see image-related things in `sitmap.xml`.

References:
1. [Nuxt Sitemap](https://nuxtseo.com/sitemap/integrations/content)
2. [Nuxt Sitemap images](https://nuxtseo.com/sitemap/guides/images-videos)
3. [CodeSandBox Reproduction of the issue](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fpages%2Fdocs%2F%5B...slug%5D.vue%3A15%2C1)

Is there any way to achieve this?

**Comment by harlan-zw** [comment]
Did you try following [Automatic Image Discovery](https://nuxtseo.com/sitemap/guides/images-videos#automatic-image-discovery)?

**Comment by Aravinda93** [comment]
@harlan-zw 
Thanks a lot for the response. As per mentioned in the document i wrapped my `layouts/default.vue` with `<main>` something like this:

```
<!-- Page Content -->
<div class="w-full flex flex-col flex-grow">
  <main>
    <slot />
  </main>
</div>
```

Previously I was just using the ` <slot />`. Even after adding the `<main>` when I generate the `.output` I don't see image related things in `sitmap.xml`. Do I need to do anything else as well? I have following in my `nuxt.config.js`:

```
 modules: [
    "@nuxtjs/tailwindcss",
    "unplugin-fonts/nuxt",
    "@nuxtjs/i18n",
    "@nuxt/content",
    "@nuxtjs/color-mode",
    "@nuxt/image",
    "@nuxtjs/sitemap"
  ],

  //To support and display the .md files from /content using @nuxt/content
  content: {
    documentDriven: true,
    sitemap: true,
    //To get the reading time for each .md file in /content
    markdown: {
      remarkPlugins: ["remark-reading-time"],
    },
    //To build the sitemap for SEO automatically using @nuxt/sitemap
    strictNuxtContentPaths: true
  },
```

Do I need to add anything for the `sitemap` to include automatically everything?

**Comment by Aravinda93** [comment]
> Did you try following [Automatic Image Discovery](https://nuxtseo.com/sitemap/guides/images-videos#automatic-image-discovery)?

@harlan-zw I tried the approach you mentioned but seems like its not working. Any suggestion, please?

**Comment by harlan-zw** [comment]
Sorry looks like I missed that part. The quickest and easiest way for me to help you is by providing a reproduction, there's even already a Nuxt Content starter for you https://stackblitz.com/edit/nuxt-starter-a5qk3s?file=nuxt.config.ts

**Comment by Aravinda93** [comment]
@harlan-zw 
Thanks a lot for the response. Sorry, I should have given you the code sample. I have created a similar repo as my original project on [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fpages%2Fdocs%2F%5B...slug%5D.vue%3A15%2C1). Can you please have a look and provide some solutions on the automatic generation of sitemap for images in the Nuxt Content project?

I have my contents/images in `/docs/introduction` and `/docs/basics` and I have 3 images in my `public/img` repo but for some reason I do not see anything within my `sitemap.xml` when I run `npm run generate`

**Comment by Aravinda93** [comment]
> Sorry looks like I missed that part.
> 
> The quickest and easiest way for me to help you is by providing a reproduction, there's even already a Nuxt Content starter for you https://stackblitz.com/edit/nuxt-starter-a5qk3s?file=nuxt.config.ts
> 
> You've given me a lot of information but not a lot I can do without replicating the issue, this feature works as far as I know, there are tests in place for it.

As per your request I have added my reproduction code here [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fpages%2Fdocs%2F%5B...slug%5D.vue%3A15%2C1) if you get a chance can you please have a look and provide some solution?

**Comment by Aravinda93** [comment]
> Sorry looks like I missed that part.
> 
> The quickest and easiest way for me to help you is by providing a reproduction, there's even already a Nuxt Content starter for you https://stackblitz.com/edit/nuxt-starter-a5qk3s?file=nuxt.config.ts
> 
> You've given me a lot of information but not a lot I can do without replicating the issue, this feature works as far as I know, there are tests in place for it.

@harlan-zw 

As per your request I have added my reproduction code here [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fpages%2Fdocs%2F%5B...slug%5D.vue%3A15%2C1) if you get a chance can you please have a look and provide some solution?

**Comment by Aravinda93** [comment]
> Sorry looks like I missed that part.
> 
> The quickest and easiest way for me to help you is by providing a reproduction, there's even already a Nuxt Content starter for you https://stackblitz.com/edit/nuxt-starter-a5qk3s?file=nuxt.config.ts
> 
> You've given me a lot of information but not a lot I can do without replicating the issue, this feature works as far as I know, there are tests in place for it.

@harlan-zw As per your request I have added my reproduction code here [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fpages%2Fdocs%2F%5B...slug%5D.vue%3A15%2C1) if you get a chance can you please have a look and provide some solution?

**Comment by harlan-zw** [comment]
I had a look at this and it seems like the regex parsing was broken for the `NuxtImg` output.

I've pushed up a fix which is in v6.0.0-beta.4 of the sitmeap module, you can upgrade to it by deleting your lock file + node_modules and re-installing.

If you still have issues please use this as a reproduction https://stackblitz.com/edit/nuxt-starter-a5qk3s?file=app.vue, the codesandbox has issues running.

**Comment by Aravinda93** [comment]
> I had a look at this and it seems like the regex parsing was broken for the `NuxtImg` output.
> 
> I've pushed up a fix which is in v6.0.0-beta.4 of the sitmeap module, you can upgrade to it by deleting your lock file + node_modules and re-installing.
> 
> If you still have issues please use this as a reproduction https://stackblitz.com/edit/nuxt-starter-a5qk3s?file=app.vue, the codesandbox has issues running.

@harlan-zw 

Thanks a lot for the response and quick fix. As per you suggestion I did the following in my project:

1. Remove all the things: `rm -Rf .output .nuxt node_modules package-lock.json`.

2. Update the version: `"@nuxtjs/sitemap": "^6.0.0-beta.4",`

3. Ran the: `npm install`

4. Run: `npm run generate`

5. Observe the `.output/public/__sitemap__/en.xml` for all the images using automatic discovery.

For some reason I am still unable to get any images in my `sitmap.xml` file when using `Nuxt Content and Nuxt Sitemap`. I tried in my original project as well as on [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5). It did not work in both places.

As requested by you I tried on [Stackblitz](https://stackblitz.com/edit/nuxt-starter-89ykte) but for some reason unable to upload dummy images there and it suddenly breaks for some reason not sure why. I am facing some issues on Stackblitz.

I have updated code in both [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5) and on [Stackblitz](https://stackblitz.com/edit/nuxt-starter-89ykte).

Can you please have a look and let me know how to get the images in `Sitemap.xml` using the [Automatic Image Discovery](https://nuxtseo.com/sitemap/guides/images-videos#automatic-image-discovery)

Thanks a lot in advance.

**Comment by Aravinda93** [comment]
@harlan-zw 

I also tried using the `components/content/ProseImg.vue` to force the images to be rendered as `NuxtImg` and passed the images in `.md` files as:

```
![Image1.](/img/Image1.png)
```

Then I ran the `npm run generate` even then I do not get the images in my `Sitemap.xml` file. I tried in my original project as well as in the [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5) did not work on either of them.

**Comment by Aravinda93** [comment]
@harlan-zw 

Just wanted to confirm if I can try something to fix the issue. Anything is required from my side for you to fix the issue?

**Comment by Aravinda93** [comment]
@harlan-zw 

Is there any alternative way or work-around to fix the issue for now until the final fix has been added to @nuxt/sitemap? Looking forward to some approach or fix.

**Comment by harlan-zw** [comment]
The issue seems to be quite simple, you have disabled `ssr` which means that when Nuxt prerenders the site, it won't prerender using the server. This means that none of the page content is available to the Sitemap module.

If you're using `nuxt generate`, there's no harm in having `ssr` enabled as it will always produce an output that doesn't rely on a server.

Saying that I did do some testing with your setup and noticed some duplicate `loc` and `alternative` entries which I've pushed up a fix for in the latest RC.

**Comment by Aravinda93** [comment]
@harlan-zw 

Thanks a lot for the response, with `ssr:true`, I am able to get some routes but I run into various errors during the process. Also, I have few tags in my `.md` files and if the `tags` have spaces then the spaces are retained in the generated URL within the `sitemap.xml` file.  Can you please let me know how to fix this?

Please once let me know how to fix the issue. Because with `ssr:false` I do not get any of the issues during `nuxt generate`. Following is my code in the [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fnuxt.config.js). [Generated SiteMap.xml](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2F.output%2Fpublic%2F__sitemap__%2Fen.xml)

Following are the errors that I get during the generation:

<details>
  <summary>Sitemap.xml Errors during the ssr:true</summary>

```javascript

[9:20:40 PM]  WARN  Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap_index.xml.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.

ℹ Prerendering 6 initial routes with crawler                                                                                                                                         nitro 9:20:41 PM
  ├─ /__sitemap__/style.xsl (18ms)                                                                                                                                                    nitro 9:20:41 PM
  ├─ /404.html (143ms)                                                                                                                                                                nitro 9:20:41 PM
  ├─ /200.html (144ms)                                                                                                                                                                nitro 9:20:41 PM
  ├─ /api/_content/cache.1725052821479.json (190ms)                                                                                                                                   nitro 9:20:41 PM
  ├─ /ui/ (256ms)                                                                                                                                                                     nitro 9:20:41 PM
  │ └── Error: [404] 
  ├─ / (254ms)                                                                                                                                                                        nitro 9:20:41 PM
  ├─ /_payload.json?b08843fd-bd7e-4fa8-9d0c-5eb443ea2da1 (15ms) (skipped)                                                                                                             nitro 9:20:41 PM
  ├─ /api/_content/query/0CgxMh2nDn.1725052821479.json (7ms)                                                                                                                          nitro 9:20:41 PM
  │ ├── Error: [404] Document not found!
  │ └── Linked from /
  ├─ /en-sitemap.xml (10ms)                                                                                                                                                           nitro 9:20:41 PM
  ├─ /index-sitemap.xml (9ms)                                                                                                                                                         nitro 9:20:41 PM
  ├─ /api/_content/query/oWHhTkscLk.1725052821479.json (6ms)                                                                                                                          nitro 9:20:41 PM
  ├─ /sitemap.xml (9ms)                                                                                                                                                               nitro 9:20:41 PM
  ├─ /_payload.json (2ms)                                                                                                                                                             nitro 9:20:41 PM
  ├─ /api/_content/navigation/i5pZc4XEtQ.1725052821479.json (15ms)                                                                                                                    nitro 9:20:41 PM

 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'getSSRProps')                                                                                9:20:41 PM
  at ssrGetDirectiveProps (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:229:40)  
  at ./.nuxt/prerender/chunks/build/DrawflowTest-sjbpp6tp.mjs:47:216  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:442:9)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:386:12)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:502:14)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:457:7)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:386:12)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:502:14)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:506:9)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:457:7)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:386:12)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:502:14)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:457:7)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:386:12)  
  at ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:84:10)  
  at ./.nuxt/prerender/chunks/build/server.mjs:8712:16  
  at renderFnWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:308:13)  
  at ssrRenderSlotInner (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:112:17)  
  at ssrRenderSlot (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:94:3)  
  at ./.nuxt/prerender/chunks/build/default-Cy_3hxgS.mjs:10:7  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:442:9)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:386:12)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:502:14)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:457:7)  
  at ./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:384:25  
  at async renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:673:18)  
  at async Object.renderToString$1 [as renderToString] (./.nuxt/prerender/chunks/_/renderer.mjs:154:18)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:174:20)  
  at async ./.nuxt/prerender/chunks/_/renderer.mjs:254:21  
  at async Object.handler (./.nuxt/prerender/chunks/_/renderer.mjs:21:22)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1975:19)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:2266:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async generateRoute (./node_modules/nitropack/dist/chunks/prerender.mjs:116:17)  
  at async Promise.all (index 1)  
  at async Promise.all (index 2)  
  at async runParallel (./node_modules/nitropack/dist/chunks/prerender.mjs:253:3)  
  at async prerender (./node_modules/nitropack/dist/chunks/prerender.mjs:202:3)  
  at async ./node_modules/nuxt/dist/index.mjs:3615:7  
  at async build (./node_modules/nuxt/dist/index.mjs:5479:5)  
  at async Object.run (./node_modules/nuxi/dist/chunks/build.mjs:94:5)  
  at async Object.run (./node_modules/nuxi/dist/chunks/generate.mjs:55:5)  
  at async runCommand$1 (./node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1648:16)  
  at async runCommand$1 (./node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)  
  at async runMain$1 (./node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1777:7)

  ├─ /DrawflowTest (99ms)                                                                                                                                                             nitro 9:20:41 PM
  │ ├── Error: [500] 
  │ └── Linked from /

[9:20:47 PM]  WARN  Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap_index.xml.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.

  ├─ /sitemap_index.xml (8ms)                                                                                                                                                         nitro 9:20:48 PM
  ├─ /__sitemap__/en.xml (27ms)                                                                                                                                                       nitro 9:20:48 PM
                                                                                                                                                                                      nitro 9:20:48 PM
Errors prerendering:
  ├─ /ui/ (256ms)                                                                                                                                                                     nitro 9:20:48 PM
  │ └── Error: [404] 
  ├─ /api/_content/query/0CgxMh2nDn.1725052821479.json (7ms)                                                                                                                          nitro 9:20:48 PM
  │ ├── Error: [404] Document not found!
  │ └── Linked from /
  ├─ /DrawflowTest (99ms)                                                                                                                                                             nitro 9:20:48 PM
  │ ├── Error: [500] 
  │ └── Linked from /
                                                                                                                                                                                      nitro 9:20:48 PM

 ERROR  Exiting due to prerender errors.                                                                                                                                                    9:20:48 PM

  at prerender (node_modules/nitropack/dist/chunks/prerender.mjs:220:11)
  at async node_modules/nuxt/dist/index.mjs:3615:7
  at async build (node_modules/nuxt/dist/index.mjs:5479:5)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:94:5)
  at async Object.run (node_modules/nuxi/dist/chunks/generate.mjs:55:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1777:7) 



 ERROR  Exiting due to prerender errors.     
```
</details>

**Comment by Aravinda93** [comment]
> The issue seems to be quite simple, you have disabled `ssr` which means that when Nuxt prerenders the site, it won't prerender using the server. This means that none of the page content is available to the Sitemap module.
> 
> If you're using `nuxt generate`, there's no harm in having `ssr` enabled as it will always produce an output that doesn't rely on a server.
> 
> Saying that I did do some testing with your setup and noticed some duplicate `loc` and `alternative` entries which I've pushed up a fix for in the latest RC.

@harlan-zw 

Thanks a lot its working fine now with `ssr:true` and able to get the images in `sitemap.xml` file. But I am facing one small issue:

I have a few `tags` in my `.md` files; if the `tags` have spaces, then the spaces are retained in the generated URL within the `sitemap.xml ` file. Can you please let me know how to fix this?

I have a Nuxt content website with some of the markdown files in /content/index.md with tags such as:
```
  navigation:
  linkTitle: "Introduction"
  tags : ["Testing tools", "performance tests", "process automation", "supply chain management", "load tests"]
    
```

I am generating the `sitemap.xml ` using the `nuxtjs/sitemap with ssr:true ` during the generation of the sitemap it generates the URL with spaces such as:

```
 <url>
    <loc>http://localhost:3000/tags/performance tests</loc>
    <xhtml:link rel="alternate" href="http://localhost:3000/tags/performance tests" hreflang="x-default" />
    <xhtml:link rel="alternate" href="http://localhost:3000/tags/performance tests" hreflang="en" />
</url>
```

Since it generates the URL with spaces they are invalid but URLs are valid when I navigate to them then they are present with spaces:
```
http://localhost:3000/tags/performance%20tests
```

How to ensure the sitemap adds appropriate spaces and checks for valid URLs before generating the `sitemap.xml ` using Nuxt Sitemap and replacing the spaces with URL-safe characters.
