### ISSUE TITLE
 Page Indexable Robots are blocked from crawling

### ISSUE THREAD

**Issue by lixiao258** [harlan-zw/nuxt-seo#303]
### Details

![微信截图_20240823095859](https://github.com/user-attachments/assets/1cb5aaa4-9f3f-4fa0-aa20-0b43165fce55)
 Page Indexable Cannot be indexed
New project
"@nuxtjs/robots": "^4.1.3"
 "nuxt": "^3.12.4"

**Comment by harlan-zw** [comment]
Hmm I think this is a false positive in the devtools, I'll look into it 👍
