### ISSUE TITLE
How to config sitemap exclude a route by a keyword in the middle

### ISSUE THREAD

**Issue by withgogo** [harlan-zw/nuxt-seo#309]
### Describe the bug

Hi, as from the doc, sitemap exclude will work like '/xxx/**', and won't work like '/\*\*/xxx'. 
So if I want exclude the url like '/aa/**bb**/cc', 'aa/**bb**/dd', which '**bb**' is in the middle of the route. How can I achieve this?

thanks

**Comment by harlan-zw** [comment]
Hi, you can directly provide a regular expression. I've updated the docs to the below, let me know if there's still any confusion.

## Filter URLs with include / exclude

For all other cases, you can use the `include` and `exclude` module options to filter URLs.

```ts [nuxt.config.ts]
export default defineNuxtConfig({
  sitemap: {
    // exclude all URLs that start with /secret
    exclude: ['/secret/**'],
    // include all URLs that start with /public
    include: ['/public/**'],
  }
})
```

Either option supports either an array of strings, RegExp objects or a `{ regex: string }` object.

Providing strings will use the [route rules path matching](https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering) which
does not support variable path segments in front of static ones.

For example, `/foo/**` will work but `/foo/**/bar` will not. To get around this you should use regex.

### Regex Filtering

Filtering using regex is more powerful and can be used to match more complex patterns. It's recommended to pass a 
`RegExp` object explicitly.

```ts [nuxt.config.ts]
export default defineNuxtConfig({
  sitemap: {
    exclude: [
      // exclude /foo/**/bar using regex
      new RegExp('/foo/.*/bar')
    ],
  }
})
```

**Comment by withgogo** [comment]
> Hi, you can directly provide a regular expression. I've updated the docs to the below, let me know if there's still any confusion.
> 
> ## Filter URLs with include / exclude
> For all other cases, you can use the `include` and `exclude` module options to filter URLs.
> 
> ```ts
> export default defineNuxtConfig({
>   sitemap: {
>     // exclude all URLs that start with /secret
>     exclude: ['/secret/**'],
>     // include all URLs that start with /public
>     include: ['/public/**'],
>   }
> })
> ```
> 
> Either option supports either an array of strings, RegExp objects or a `{ regex: string }` object.
> 
> Providing strings will use the [route rules path matching](https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering) which does not support variable path segments in front of static ones.
> 
> For example, `/foo/**` will work but `/foo/**/bar` will not. To get around this you should use regex.
> 
> ### Regex Filtering
> Filtering using regex is more powerful and can be used to match more complex patterns. It's recommended to pass a `RegExp` object explicitly.
> 
> ```ts
> export default defineNuxtConfig({
>   sitemap: {
>     exclude: [
>       // exclude /foo/**/bar using regex
>       new RegExp('/foo/.*/bar')
>     ],
>   }
> })
> ```

Thanks Harlan. 
As your mentioned, so I want to exclude the keyword 'bb',  is the following setting correct?
```export default defineNuxtConfig({
  sitemap: {
    exclude: [
      // exclude /**/bb/** using regex
      new RegExp('/.*/bb/**')
    ],
  }
})
```

**Comment by harlan-zw** [comment]
You should use https://regex101.com/ to generate the regex.

![image](https://github.com/user-attachments/assets/b68799a4-aae7-4609-aa62-61507a87d690)
