### ISSUE TITLE
After use this seo module, my page title is combined with package.json's  "name"

### ISSUE THREAD

**Issue by withgogo** [harlan-zw/nuxt-seo#316]
### Describe the bug

As title said, title will combine the page title + package.json's name. 
i.e. "my title | ${packageName}"

How can I get rid of ${packageName}

### System / Nuxt Info

```Shell
"vue": "^3.5.3",
"nuxt": "^3.13.0",
"@nuxtjs/seo": "^2.0.0-rc.21",
```

**Comment by harlan-zw** [comment]
Hi, please see https://nuxtseo.com/nuxt-seo/guides/configuring-modules.

**Comment by withgogo** [comment]
> Hi, please see https://nuxtseo.com/nuxt-seo/guides/configuring-modules.

I've setup "site" only used "url", as I don't want to use the "name" for the title. So how can I achieve my requirement?
Can I set the "name" to null as below?

```export default defineNuxtConfig({
  site: {
    url: 'https://example.com',
    name: null
  }
})```
