### ISSUE TITLE
`discoverVideos` config

### ISSUE THREAD

**Issue by codeflorist** [harlan-zw/nuxt-seo#317]
### Clear and concise description of the problem

Auto-discovery of images can be turned off via `discoverImages: false` in the config.

The same is not possible for videos.

### Suggested solution

Add a `discoverVideos: false` config parameter.

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. This option actually does already exist but it missing documentation.

I've pushed some [improvements](https://github.com/harlan-zw/nuxt-seo/commit/6ca374b93f15992d27dda19949aee2e4817a26a4) to the docs.

```ts [nuxt.config.ts]
export default defineNuxtConfig({
  sitemap: {
    discoverVideos: false,
  }
})
```
