### ISSUE TITLE
definePageMeta > breadcrumb not accepting dynamic values

### ISSUE THREAD

**Issue by richgcook** [harlan-zw/nuxt-seo#324]
### Details

Being able to override specific page labels in the breadcrumb using definePageMeta is great but I'm unable to use dynamic values consistently in definePageMeta even though it works in useHead without problems but randomly, not all the time, I get a 500 server error `title is not defined`

An extract of my code below to demonstrate the setup but is there any reason why using title.value, which works consistently in useHead, would error out when used in definePageMeta?

```
<script setup>

...

const { data } = await useSanityQuery(query)

const { title, description, image, bodyClass } = useMetaBodyHelpers(data?.value.issuesPage)

useHead({
	title: title.value,
})

definePageMeta({
	breadcrumb: {
		label: title.value,
	},
})

</script>
```

**Comment by harlan-zw** [comment]
Hi, the `definePageMeta` only supports static values as it's a compile-time macro. You can learn more here: https://nuxt.com/docs/api/utils/define-page-meta

You should follow the docs for [overrides](https://nuxtseo.com/nuxt-seo/api/breadcrumbs#overrides) to use dynamic data.

**Comment by mavrick** [comment]
@harlan-zw are you able to provide an example of usage, i'm running into a simialr issue and using useBreadcrumbItems({ overrides: [] }); in setup() or created() has no affect

**Comment by mavrick** [comment]
> @harlan-zw are you able to provide an example of usage, i'm running into a simialr issue and using useBreadcrumbItems({ overrides: [] }); in setup() or created() has no affect

I think i've answered my own question, but there is no global way to affect the usage of useBreadcrumbItems() before the page renders afaik.

**Comment by harlan-zw** [comment]
If you're able to make a [reproduction](https://stackblitz.com/edit/nuxt-starter-gfrej6?file=nuxt.config.ts) of the issue I'll be able to provide a solution for you

**Comment by mavrick** [comment]
https://github.com/mavrick/nuxt-seo-test

folder structure: `/pages/[gameId]/events/[eventId]/`

http://localhost:3000/cs/events/test/

```json
[
  {
    "to": "/",
    "label": "Home",
    "ariaLabel": "Home",
    "current": false
  },
  {
    "to": "/cs",
    "label": "Counter Strike",
    "ariaLabel": "Counter Strike",
    "current": false
  },
  {
    "to": "/cs/events",
    "label": "Gameid Events Eventid",
    "ariaLabel": "Gameid Events Eventid",
    "current": false
  },
  {
    "to": "/cs/events/test",
    "label": "Gameid Events Eventid",
    "ariaLabel": "Gameid Events Eventid",
    "current": true
  }
]
```

"@nuxtjs/seo": "2.0.0-rc.23",

**Comment by harlan-zw** [comment]
This should be fixed in the [v2 stable](https://github.com/harlan-zw/nuxt-seo/releases/tag/v2.0.0).
