### ISSUE TITLE
Unable to install nuxt seo module

### ISSUE THREAD

**Issue by brunopbarbosa** [harlan-zw/nuxt-seo#326]
### Describe the bug

When trying to install the nuxt seo module, i hit the following warning:

 WARN  Cannot search in the Nuxt Modules database: FetchError: [GET] "https://api.nuxt.com/modules?version=all": <no response> fetch failed 
 
  WARN  It seems that seo is not a Nuxt module. 

Then it asks if i wanto to continue installing 'seo' anyway.
I tried with the sitemap and robots module and had the same experience. Is this some server issue or have I misconfigured something? Wasn't able to find any related info to this issue...

Thanks in advance!

**Comment by harlan-zw** [comment]
Seems like Nuxt's API is offline. You can install the module manually by running `pnpm add @nuxtjs/seo` or whatever package manager you're using
