### ISSUE TITLE
Missing `fallbackTitle` option from documentation

### ISSUE THREAD

**Issue by luca-smartpricing** [harlan-zw/nuxt-seo#328]
### Describe the bug

There's no reference to `fallbackTitle` option on the [page](https://nuxtseo.com/nuxt-seo/api/config). 

PS:
I think talking about the `titleTemplate` on the plugin page is a bad idea. A hint is sufficient given that the official documentation is present on the [Nuxt](https://nuxt.com/docs/getting-started/seo-meta#title-template) website. Rather it would be better to explain that the `fallbackTitle` activates or deactivates the `titleTeamplate`

**Comment by harlan-zw** [comment]
Thanks for the issue, I'm working on a big docs overhaul and will make sure this is addressed.

**Comment by harlan-zw** [comment]
https://nuxtseo.com/docs/seo-utils/guides/fallback-title#fallback-title
