### ISSUE TITLE
nitropack/runtime

### ISSUE THREAD

**Issue by Haunth** [harlan-zw/nuxt-seo#329]
### Describe the bug

I'm using nuxtjs 3.14.0. When I upgrade @nuxtjs/sitemap to latest version. I have many warning like this
nitropack/runtime" is imported by "node_modules/@nuxtjs/sitemap/dist/runtime/nitro/sitemap/nitro.js", but could not be resolved – treating it as an external dependency.

Please hekp me checking this bug and resolve

**Comment by harlan-zw** [comment]
Hi, please see https://github.com/nuxt-modules/sitemap/issues/342
