### ISSUE TITLE
problem with persian language

### ISSUE THREAD

**Issue by Alijaaan** [harlan-zw/nuxt-seo#330]
### Describe the bug

I'm not sure if this is a bug or if I did something wrong.

I'm trying to create a site in persian language.

**1. I used persian name for my page structure like this:**

![1](https://github.com/user-attachments/assets/59e332de-1a68-4138-ba64-bf5e7a947345)

**2. everything works fine :**

![2](https://github.com/user-attachments/assets/bcdce2d7-d501-4d4b-a55b-4a1295ae501e)

**3. but when I create a sitemap, the url encoded like this:**

![3](https://github.com/user-attachments/assets/8af48497-98a3-4e25-8804-a8be29c97aef)

**4. and when I click the generated link i recieve error page not found 404:**

![4](https://github.com/user-attachments/assets/1442b333-ef60-4448-a82d-c65b927c2905)

Did I do something wrong or is this a bug?

**Comment by harlan-zw** [comment]
Hi @Alijaaan, as far as I'm aware the sitemap module is doing the right thing. These characters aren't technically valid as a path, see https://webmasters.stackexchange.com/questions/11482/is-it-okay-to-use-persian-utf-8-characters-in-our-urls.

The encoding link _should_ work, this may be an upstream Nuxt issue.

**Comment by Alijaaan** [comment]
Actually, bcause of this problem and one other important issue, I had to change the whole solution for creating and managing my sitemaps and I wrote everything from the scratch.
Thanks for your answer :)

**Comment by harlan-zw** [comment]
Fair enough, thanks for letting me know.
