### ISSUE TITLE
useBreadcrumbItems only returns items with `label: "Slug"`

### ISSUE THREAD

**Issue by TimDirks** [harlan-zw/nuxt-seo#334]
### Describe the bug

Using the `useBreadcrumbItems` composable returns the items with the correct `to` and `current` property, however every `label` and `ariaLabel` now says "Slug". This can even be seen on the site of the package itself;

<img width="785" alt="Screenshot 2024-10-14 at 14 08 08" src="https://github.com/user-attachments/assets/af5332a9-78de-43db-8d17-25d600264fd1">

### Reproduction

https://nuxtseo.com/nuxt-seo/api/breadcrumbs#demo

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. I'm in the middle of quite a big refactor of the docs and migrating the breadcrumbs to the newly renamed [nuxt-seo-utils](https://github.com/harlan-zw/nuxt-seo-utils/pull/24). 

If you need a fix please see that repo otherwise will try and land it asap.

**Comment by harlan-zw** [comment]
Agreed, thanks for investigating. I've pushed up a fix in nuxt-seo-utils which will be released soon.
