### ISSUE TITLE
Website not showing icons

### ISSUE THREAD

**Issue by hareland** [harlan-zw/nuxt-seo#337]
### Describe the bug

Website showing icon names instead of icons.
I have done multiple hard refresh.

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/99cdb047-1c67-4976-b1b0-34838d38952c">

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/0976d10a-c4aa-4d83-886e-6c8e31266400">

### Reproduction

Go to https://nuxtseo.com

### System / Nuxt Info

```Shell
MacOS 15.0.1, 
Chrome Version 129.0.6668.91 (Official Build) (arm64)
```

**Comment by Dino-Kupinic** [comment]
same here

**Comment by harlan-zw** [comment]
Will fix shortly, thanks for flagging.

**Comment by harlan-zw** [comment]
Partially fixed, the home page is throwing an error I'm investigating.

**Comment by harlan-zw** [comment]
Seems fixed
