### ISSUE TITLE
How to set dynamic `siteName` and `language`?

### ISSUE THREAD

**Issue by stefanobartoletti** [harlan-zw/nuxt-seo#34]
### Details

I need to define these two properties by accessing dynamic data from a CMS, and especially for the language, it should be relative to a single page and not generic for the entire site (think about multilanguage websites).

According to the docs, this is the default minimal config

```
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL || 'https://example.com',
      siteName: 'Awesome Site',
      siteDescription: 'Welcome to my awesome site!',
      language: 'en', // prefer more explicit language codes like `en-AU` over `en`
    }
  },
})
```

Is it possible to have these two properties set at the component level?

**Comment by harlan-zw** [comment]
Hey @stefanobartoletti 

You can provide these directly to the SeoKit component but it won't propagate for all of the submodules.

```vue
<template>
   <SeoKit 
     :site-name="data.siteName"
     :language="data.language"
    />
</template>
```

I'm working on some improvements around this, so let me know if / where you get stuck and I'll make sure it's fixed.

Also proper i18n integration is in the works

**Comment by stefanobartoletti** [comment]
Thanks for your reply.

Can I ask you what you exactly mean by "it won't propagate for all of the submodules"?

Is there some specific place where the SeoKit component should be placed to be effective?

**Comment by harlan-zw** [comment]
> Thanks for your reply.
> 
> Can I ask you what you exactly mean by "it won't propagate for all of the submodules"?
> 
> Is there some specific place where the SeoKit component should be placed to be effective?

So given your example, the Schema.org module wouldn't change its default language if you changed the language at runtime.

This isn't a major issue though, you would just need to make sure you're providing the content the language is in if you implement it.

The only props otherwise which would have issues would be:
- siteUrl (robots, og image, schema.org, sitemap)
- trailingSlash (sitemap, schema.org)
- indexable (robots)

**Comment by harlan-zw** [comment]
> Ok, understood, thank you. At the moment the only attribute that I really need to fix is the siteName, and the issue is possibly related to #25 (I am experiencing the same problem apparently).
> 
> I tried to upgrade to version 1.3.1, but now it seems that wildcards are not correctly replaced by real values, at least in my configuration
> 
> ![Screenshot_20230227_172800](https://user-images.githubusercontent.com/36746429/221639232-571214ea-b607-4005-bfe7-304207a54737.png)

Try update your lock file, Nuxt is still likely using the old version of Unhead

**Comment by stefanobartoletti** [comment]
Ok, I tried to delete yarn.lock and let it be rebuilt from scratch.

The problem with the wildcards is now solved, but I have these new issues:

- launching `yarn dev` complained that `ws` was not found (I think is a sub-dependency of ` nuxt-seo-kit`), I had to manually add it as a peer dependency in my project.
- `site-name` is still not set correctly if I use `<SeoKit site-name="Lorem Ipsum" />`; I can only set this value from Nuxt config. If I don't set it from Nuxt config, a default "Nuxt Playground" is used.


This is my `nuxi info`:

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `modules`, `extends`, `runtimeConfig`, `image`, `app`, `experimental`
- Runtime Modules:  `@storyblok/nuxt@5.2.0`, `@nuxtjs/tailwindcss@6.4.1`, `nuxt-icon@0.3.2`, `@vueuse/nuxt@9.13.0`, `@nuxt/image-edge@1.0.0-27954023.4cee565`
- Build Modules:    `-`
------------------------------
```


By the way, thank you very much for your time and effort in trying to help me!

**Comment by stefanobartoletti** [comment]
After updating to version `1.3.4` a lot of things seem to be solved.

First of all thank you very much for your efforts!

I still have a very little problem, namely in the `og:title` property:

![Screenshot_20230308_145359](https://user-images.githubusercontent.com/36746429/223746675-6ad138e3-5fe1-455e-aa8f-b370f66f149d.png)
![Screenshot_20230308_145407](https://user-images.githubusercontent.com/36746429/223750103-ac40a849-3efd-4c3a-9246-2a1f96b72d85.png)


The Site Name as set on the component does not seem to work correctly with `og:title`, it used as set on Nuxt Config, or not used at all if the value in Nuxt Config is absent (it would just be `Home Title` in my example)

This isthe current configuration I have:

```js
// nuxt.cofig.ts
  runtimeConfig: {
    public: {
      // other configs
      siteName: 'Site Name from Nuxt Config',
      // other configs
    },
  },
```

and

```vue
<template>
  <div class="flex min-h-screen flex-col">
    <SeoKit site-name="Site name from component" language="it" />
    <SiteHeader />
    <DebugHead />
    <slot></slot>
    <SiteFooter />
  </div>
</template>
```

As you can see,

**Comment by Ben-VP** [comment]
I'm having the same issue with 'og:title'. It's not adding the title separator and the site name.

**Comment by austriker27** [comment]
> Hey @stefanobartoletti
> 
> You can provide these directly to the SeoKit component but it won't propagate for all of the submodules.
> 
> ```
> <template>
>    <SeoKit 
>      :site-name="data.siteName"
>      :language="data.language"
>     />
> </template>
> ```
> 
> I'm working on some improvements around this, so let me know if / where you get stuck and I'll make sure it's fixed.
> 
> Also proper i18n integration is in the works

@harlan-zw Can we provide a dynamic site url to the Og Image component? Is there a workaround until SeoKit will propogate `site-url` for all its submodules)?

I tried passing it in like the below example -- but it didnt work

```
defineOgImageStatic({
    component: 'DefaultOgImage',
    siteUrl: 'https://web-v2.test',
})
```

And in `app.vue`: 
```
<SeoKit :site-url="baseUrl" />

```

**Comment by harlan-zw** [comment]
This is a core issue being resolved in v2 of nuxt-seo-kit which is currently close to being released in a beta. I'll provide details to you as soon as I have migrated all my personal sites to it without issue.

**Comment by productdevbook** [comment]
We should be able to add it in the plugin, I just don't want to change it in nuxt.config.ts `defineNuxtConfig`

**Comment by harlan-zw** [comment]
> We should be able to add it in the plugin, I just don't want to change it in nuxt.config.ts `defineNuxtConfig`

Agreed. I have a module called `nuxt-site-config` that will take care of this logic in v2, still experimenting, it will be public soon.

Will include full support for runtime changes.

**Comment by harlan-zw** [comment]
Please see https://nuxtseo.com/site-config/guides/runtime-site-config
