### ISSUE TITLE
New version of nuxt-seo-utils v.5.0.0 with @nuxtjs/seo@2.0.0-rc.23

### ISSUE THREAD

**Issue by Met96** [harlan-zw/nuxt-seo#340]
### Details

When it will be available the newest version of nuxt-seo-utils v.5.0.0 released yersterday for @nuxtjs/seo ?

**Comment by harlan-zw** [comment]
Unfortunately this won't be available until the v2 stable is ready as there is some final minor breaking changes. 

It's currently blocked on the new docs and some more tests, it will maybe be a week or so away.

**Comment by haakonmt** [comment]
@harlan-zw Any update on this? 🤞

**Comment by harlan-zw** [comment]
Sorry for the delay, available now in the [v2 stable](https://github.com/harlan-zw/nuxt-seo/releases/tag/v2.0.0).
