### ISSUE TITLE
Broken breadcrumbs snippet

### ISSUE THREAD

**Issue by cyrilf** [harlan-zw/nuxt-seo#342]
### Additional context

**tl;dr;** A typo has been fixed and is not visible on the live website.

----

Hey, I saw that [this page about breadcrumb-raw](https://nuxtseo.com/nuxt-seo/api/_breadcrumb-raw) contains a typo.
It show `<li v-for="(item, key) in items" :key="key">` where `items` should be `links`.

I was going to fix it and submit a PR, but.. someone already did it 5 months ago.
You [can see the commit here](https://github.com/harlan-zw/nuxt-seo/commit/2dfef41e44ab0a385b13f6cd2540077b5ea32a23).

So this is just a heads up to let you know that it doesn't seem to be deployed.. it's on the `v2` branch.

**Comment by harlan-zw** [comment]
Hi, thanks for flagging this. It is now fixed in the latest docs.
