### ISSUE TITLE
 ERROR [worker reload] [worker init] Package import specifier "#internal/nitro/virtual/plugins"

### ISSUE THREAD

**Issue by charbs-io** [harlan-zw/nuxt-seo#343]
### Details

Hi, 

I'm getting this error when I install @nuxtjs/seo on a new build. 

`ERROR  [worker reload] [worker init] Package import specifier "#internal/nitro/virtual/plugins" is not defined in package SITE_NAME/node_modules/nitropack/package.json imported from SITE_NAME/node_modules/nitropack/dist/runtime/app.mjs`

`package.json`
```
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "start": "node .output/server/index.mjs"
  },
  "dependencies": {
    "@nuxt/image": "^1.8.1",
    "@nuxt/ui": "^2.18.6",
    "@nuxtjs/google-fonts": "^3.2.0",
    "@nuxtjs/mdc": "^0.9.2",
    "@nuxtjs/seo": "^2.0.0-rc.23",
    "@types/dompurify": "^3.0.5",
    "date-fns": "^4.1.0",
    "dompurify": "^3.1.7",
    "h3-compression": "^0.3.2",
    "nuxt": "^3.13.2",
    "nuxt-time": "^1.0.2",
    "vue": "latest",
    "vue-router": "latest"
  }
}
```

I've used @nuxtjs/seo many times before (weirdly same nuxt and nuxtjs/seo versions) without any issues.

Is any having trouble with this too?

Thanks

**Comment by remihuigen** [comment]
I'm encountering this error when i use @nuxtjs/seo as a dependency in a layer. 

even though the target app nuxt.config installs the layers deps, i need to add @nuxtjs/seo to the target apps devDeps for this error to disappear

I'm currently using @2.0.0-rc.23

```
extends: [
    [`github:<repo>`, { auth: process.env.GIGET_AUTH, install: true }],
  ],
```

**Comment by harlan-zw** [comment]
If I can find a way to reliable replicate this I can likely find the issue but until then I'm not too sure, I'm quite certain it's an upstream issue OR it's a hoisting bug.

You can try `nuxi upgrade --latest` and `pnpm -i shamefully-hoist` and see what happens

**Comment by harlan-zw** [comment]
Going to close as not much I can do without a reproduction
