### ISSUE TITLE
Multiple inconsistent ways of defining a site url

### ISSUE THREAD

**Issue by cyrilf** [harlan-zw/nuxt-seo#345]
## :one: Various `.env` variables names in the doc

On the site config [Getting started page](https://nuxtseo.com/docs/site-config/getting-started/installation), in the `Site Config Quick Setup` block it mentions that we can use the following keys in the `.env` file:
```yml
NUXT_PUBLIC_SITE_URL=https://example.com
NUXT_PUBLIC_SITE_NAME=My Awesome Website
```

But if I open the guide [setting site config / Environment specific site config](https://nuxtseo.com/docs/site-config/guides/setting-site-config#environment-specific-site-config) (which I need, because I have local, preprod and prod environments) it says:

```yml
NUXT_SITE_URL=https://test.example.com
NUXT_SITE_NAME="STAGING SITE NAME"
NUXT_SITE_ENV="staging"
```

which is **not** the same keys.

So I'm wondering which one is the most recommended?

## :two: Runtime config mapping to .env

On the [Nuxt runtime config documentation](https://nuxt.com/docs/guide/going-further/runtime-config#example) they explicitly say that something like that in the `.env`:
```yml
NUXT_API_SECRET=api_secret_token
NUXT_PUBLIC_API_BASE=https://nuxtjs.org
```

will match this in the `nuxt.config.ts` file:
```ts
export default defineNuxtConfig({
  runtimeConfig: {
    apiSecret: '', // can be overridden by NUXT_API_SECRET environment variable
    public: {
      apiBase: '', // can be overridden by NUXT_PUBLIC_API_BASE environment variable
    }
  },
})
```

so I'm wondering why your example refers to:
```yml
NUXT_PUBLIC_SITE_URL=https://example.com
NUXT_PUBLIC_SITE_NAME=My Awesome Website
```
for

```ts
export default defineNuxtConfig({
  site: {
    url: 'https://example.com',
    name: 'My Awesome Website' 
   }
})
```

shouldn't it be that instead:
```ts
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      site: {
        url: 'https://example.com',
        name: 'My Awesome Website' 
      }
    }
   }
})
```
----

Thanks a lot for the clarifications! :ok_hand:

**Comment by cyrilf** [comment]
Ok, I think that digging in the code is a good way of finding an answer :wink: 
So I think that the answer lies somewhere in [this file](https://github.com/harlan-zw/nuxt-site-config/blob/main/packages/kit/src/init.ts#L7-L83) or [this one](https://github.com/harlan-zw/nuxt-site-config/blob/ad564043bc3a09d6692313a55031f70a51467ee3/packages/site-config/src/utils.ts)

So both `NUXT_SITE_` and `NUXT_PUBLIC_SITE_` are supported in the `.env`. Do you recommend one of them?
The runtimeConfig in `nuxt.config.ts` is mentioned as [legacy](https://github.com/harlan-zw/nuxt-site-config/blob/ad564043bc3a09d6692313a55031f70a51467ee3/packages/kit/src/init.ts#L72) though..

**Comment by harlan-zw** [comment]
Hi, this is a good question (sorry for the delay).

The number of ways you can configure site config is a relic of how previous module version majors wanted this config. I realize it's confusing and there are too many options.

The recommendation is not to use runtimeConfig, either use `site.*`, env keys without public `NUXT_SITE_` or use the hooks. But it's honestly up to you, whatever works for your site is the recommendation.

I've tried to clean up the doc related to this so will close for now as not too sure what else I can do without further breaking changes.
