### ISSUE TITLE
`useBreadcrumbItems()` is not returning correct labels on latest versions

### ISSUE THREAD

**Issue by stefanobartoletti** [harlan-zw/nuxt-seo#353]
### Describe the bug

`useBreadcrumbItems()` in the latest package versions is not working correctly, instead of returning the correct `label` value, it returns a generic "slug"

a simple console log 

```js
const crumbs = useBreadcrumbItems()
console.log(crumbs)
```

returns this:

![Screenshot_20241115_014354](https://github.com/user-attachments/assets/f29b6d16-d189-4d98-94c9-246af7d05f8a)

while previously, and up to version `v2.0.0-rc.21`, it correctly returned real labels:

![Screenshot_20241115_014737](https://github.com/user-attachments/assets/fadd96bf-70d7-4406-8c83-fa7f91268259)

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v18.20.4
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @storyblok/nuxt@6.2.0, @nuxtjs/tailwindcss@6.12.2, @vueuse/nuxt@11.2.0, @nuxtjs/seo@2.0.0-rc.21, @nuxt/image@1.8.1, @nuxt/devtools@1.6.0, @vee-validate/nuxt@4.14.7, @stefanobartoletti/nuxt-social-share@1.2.0, @nuxtjs/mdc@0.9.2, dayjs-nuxt@2.1.11, @tresjs/nuxt@3.0.7, @pinia/nuxt@0.7.0, @nuxt/eslint@0.6.1, @nuxt/icon@1.7.2
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Hi, please try with the [v2 stable](https://github.com/harlan-zw/nuxt-seo/releases/tag/v2.0.0).
