### ISSUE TITLE
Locale based sitemaps styling issue

### ISSUE THREAD

**Issue by ALABOET** [harlan-zw/nuxt-seo#354]
### Details

Hello everyone. This problem has been bugging me for a while now.
so i have a site with 2 locales - En and Ru. when i used to have i18n strategy: no_prefix, i would get only 1 sitemap.xml, but it would be styled in a tree way.
when i changed strategy to prefix_except_default, app started generation sitemap_index.xml (first image)

![image](https://github.com/user-attachments/assets/65d7afc4-5928-435e-bc8b-41c8c7e3a395)
BUT should i go to say en-sitemap.xml, i get this (second image) 

![image](https://github.com/user-attachments/assets/7d2064ee-84de-4638-a3e3-27eea6f10a3c)
As you can see, no styling is applied, which is normal since xsl: false, but at the same time /sitemap_index.xml is still styled the way i want all 3 pages to look!
i am thinking it may have something to do with my nuxt 3 nxut condig setup, with xsl: false.
sitemap: {
    xsl: false,
    trailingSlash: true,
    hostname: 'https://www.tsunami.cash',
    gzip: true,
    exclude: [
      '/user/**',
      '/auth/**',
      '/error/**',
      '/success/**',
      '/articles/authors',
    ],
    // sources: ['/api/sitemap'],
  },
 
  i18n: {
    lazy: true,
    langDir: './assets/locales',
    locales,
    strategy: 'prefix_except_default',
    defaultLocale: 'ru',
    compilation: {
      strictMessage: false,
    },
  },
  the issue here is that if i remove xsl: false, then yeah, i get some styling (not the kind that i want - document tree) for all 3 pages, but not the type i am looking for (image 3) 
  
![image](https://github.com/user-attachments/assets/a27f494b-5d55-4f89-b5e3-ff76130fda0a)
 my question here is: is there a way i could make this wanted tree like style for all 3 pages, not just for main one? and why does this happen in the first place? thanks a lot!

**Comment by harlan-zw** [comment]
I looked into this issue many months ago, I found that it's actually a Chrome bug rendering the i18n sitemaps when you have styling disabled. There's nothing I can do on my end to fix it, unfortunately.

You can verify it's not an issue on your end by submitting to google search console and verifying there's no errors.
