### ISSUE TITLE
@nuxtjs/sitemap routes alias

### ISSUE THREAD

**Issue by ElYaiko** [harlan-zw/nuxt-seo#355]
### Describe the bug

The module `sitemap` is not extracting the alias defined in routes?
ex:

```
  definePageMeta({
    name: 'faq',
    alias: ['/frequent-questions'],
  });
```

It only extracts '/faq' but not '/frequent-questions'.

### System / Nuxt Info

```Shell
6.1.5
```

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. I'm not really sure how to support this given we should only be adding in the canonical URL, if we add both we have duplicate content.

I'll close for now but happy to discuss further if you think there's a solution.

**Comment by ElYaiko** [comment]
> Hi, thanks for the issue. I'm not really sure how to support this given we should only be adding in the canonical URL, if we add both we have duplicate content.
> 
> I'll close for now but happy to discuss further if you think there's a solution.

Hi thanks,
I understand your point of view, maybe this could be added as an optional option?, like:
`sitemap: { includeRouteAlias: true }`

This may be good for seo, I don't think is an issue to add "duplicated content"
