### ISSUE TITLE
Small mistake in Nuxt SEO installation docs

### ISSUE THREAD

**Issue by michaelreinhard1** [harlan-zw/nuxt-seo#356]
### Details

Hi, I noticed a small detail in the Nuxt SEO installation docs: https://nuxtseo.com/docs/nuxt-seo/getting-started/installation. It says adding `nuxt-og-image` to the modules but it should be `@nuxtjs/seo`. Thanks for taking a look!

![afbeelding](https://github.com/user-attachments/assets/b580f507-4c50-4c09-a53e-c233e428664e)

**Comment by harlan-zw** [comment]
Thanks! Have pushed up a fix :)
