### ISSUE TITLE
titleTemplate: `titleChunk` is undefined in `og:title` and `ogTitle` has no effect in `useServerSeoMeta`

### ISSUE THREAD

**Issue by stephiescastle** [harlan-zw/nuxt-seo#357]
### Describe the bug

When providing a `titleTemplate` in app.vue, it appears that `titleChunk` is undefined when generating the `og:title` meta tag.

I tried to override `og:title` by setting `ogTitle` in `useServerSeoMeta`, and it has no effect on the `og:title` tag. If I remove the `titleTemplate` from app.vue, `ogTitle` works as expected.

### Reproduction

To come. I will update this issue.

### System / Nuxt Info

```Shell
"@nuxtjs/seo": "2.0.0-rc.21",
    "nuxt": "^3.13.1",


  System:
    OS: macOS 14.7.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 659.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.5.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.70
    Edge: 131.0.2903.51
    Safari: 18.1
```

**Comment by harlan-zw** [comment]
Hi, I'd recommend using a string titleTemplate over a function, please see this guide for working with titles like this: https://nuxtseo.com/learn/mastering-meta/titles#social-share-titles-in-vue

If you still have issues then please provide a reproduction and I'll re-open and take a look.
