### ISSUE TITLE
feat: Node 20 support

### ISSUE THREAD

**Issue by unluckynelson** [harlan-zw/nuxt-seo#364]
### 🆒 Your use case

Any news on when node 20 will be supported?

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@nuxt/kit@3.4.2',
npm warn EBADENGINE   required: { node: '^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0' },
npm warn EBADENGINE   current: { node: 'v20.18.1', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@nuxt/schema@3.4.2',
npm warn EBADENGINE   required: { node: '^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0' },
npm warn EBADENGINE   current: { node: 'v20.18.1', npm: '10.8.2' }
npm warn EBADENGINE }
```

![image](https://github.com/user-attachments/assets/d374bb05-9b47-4e5c-ae72-f9dc7453da86)
![image](https://github.com/user-attachments/assets/68b738d2-7f38-44a3-8645-2d12b5ca5a54)

### 🆕 The solution you'd like

Node 20 support

**Comment by harlan-zw** [comment]
Hey, you're using a super old version of Nuxt SEO, it was renamed from Nuxt SEO Kit ages ago.

I'd suggest upgrading to the latest:
- [Nuxt SEO Kit to Nuxt SEO Beta](https://nuxtseo.com/docs/nuxt-seo/migration-guide/nuxt-seo-kit)
- [Nuxt SEO Beta to RC](https://nuxtseo.com/docs/nuxt-seo/migration-guide/beta-to-rc)
- [Nuxt SEO RC to Stable](https://nuxtseo.com/docs/nuxt-seo/migration-guide/rc-to-stable)
