### ISSUE TITLE
fix: Imports scan false breaks `nuxt-schema-org` and `@nuxtjs/seo`

### ISSUE THREAD

**Issue by Robbe95** [harlan-zw/nuxt-seo#365]
### 🐛 The bug

When you disable scan in your nuxt.config.ts, like this
```  
imports: {
  scan: false,
},
```
You get the following errors and a 500 when reloading the page.
 ```
ERROR  Pre-transform error: [unimport] failed to find "useSiteConfig" imported from "#imports"                                     13:55:44
 ERROR  Pre-transform error: [unimport] failed to find "createSitePathResolver" imported from "#imports"                            13:55:44
```

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-kfks6g?file=pages%2Findex.vue,pages%2Fabout.vue,nuxt.config.ts

### 🌈 Expected behavior

The modules work like expected.

**Comment by harlan-zw** [comment]
Thanks, I was waiting for an issue like this as I think more people will move towards disabling auto imports for Nuxt v4.

The issue is fixed with v4.0.3 of `nuxt-schema-org`: https://stackblitz.com/edit/nuxt-starter-1g7pgtnx?file=package.json
