### ISSUE TITLE
Problem with prerendering

### ISSUE THREAD

**Issue by lukaszflorczak** [harlan-zw/nuxt-seo#45]
### Details

Hi there!

I have encountered a problem where after using `nuxt-seo-kit` and building the application, Nuxt is using prerendered data. I have a website that has multiple landing pages, which fetch some content from CMS. The intention is for this data to be fetched dynamically. However, Nuxt with `nuxt-seo-kit` always uses prerendering regardless of the settings in `routeRules`. Disabling `swr` and forcing `ssr` did not help, as I always received data from the build time on the server-side.

I'm not sure if it's possible, but since the sitemap and broken-link-checker require prerendering to work, it should only be activated if these modules are active (I see in the code, it's enabled in the config regardless of the use of sitemap and broken-link-checker), and then the data should be cleared in some way.

Finally I used this config:
```js
  nitro: {
    prerender: {
      crawlLinks: false,
      routes: [],
      ignore: ['/'],
    },
  },
```
but it's more of a workaround than a solution to the problem.

**Comment by lukaszflorczak** [comment]
Thanks for the info. I will waiting for the next version.

**Comment by Sandros94** [comment]
It took me quite a while to understand why swr wasn't working, since it is incompatible with prerendering.

Could we add this note in the related FAQs, till v2 is out?
