### ISSUE TITLE
Setup nuxt seo kit with histoire 

### ISSUE THREAD

**Issue by jordan-boyer** [harlan-zw/nuxt-seo#55]
I've try to setup histoire on my nuxt app but it fail because of a dep of seo kit

I've already created an issue in the histoire repository but I'm still posting here in case you might know how to solve it
 https://github.com/histoire-dev/histoire/issues/520

**Comment by harlan-zw** [comment]
LMK if this is still an issue with v2, if so I'll investigate further.
