### ISSUE TITLE
Completely overwrite title

### ISSUE THREAD

**Issue by tobiasdiez** [harlan-zw/nuxt-seo#57]
### Clear and concise description of the problem

All pages should have a title of the form `%s - %siteName` except for a single page (the root), which should have a completely different name. Simply setting `title = xyz` in the root page doesn't work, since this would generate a title `xyz - site`, instead of the desired `xyz`.

### Suggested solution

Provide a way to completely overwrite the title or title template for a given page.

**Comment by harlan-zw** [comment]
In v2 you should just be able to provide a null `titleTemplate` within your `index.vue`.

```ts
useHead({
  titleTemplate: null,
  title: 'No template',
})
```
