### ISSUE TITLE
SEO Kit breaks route rules

### ISSUE THREAD

**Issue by marcelxpfeifer** [harlan-zw/nuxt-seo#67]
### Describe the bug

I was using this module to optimize a website for SEO. The website was rendered on Netlify with some custom routeRules set in the nuxt.config.js after installing this module all routes were pre-rendered.

I guess this is due to the nitro config inside this modules layer.

To fix the issue I installed all modules combined in this module.

**Comment by harlan-zw** [comment]
Hi @marcelxpfeifer 

The v1 of this module requires prerendering all pages for the functionality to work correctly. The v2 is in active development and solves this. Any of the submodules which are => v2 are ready to go.

**Comment by marcelxpfeifer** [comment]
> 

Yes you can simply install every single package (some are still in beta for v2), but like @harlan-zw this will be fixed with v2 of this package.

**Comment by plcdnl** [comment]
Is it possible that this continues to happen in v2?

**Comment by harlan-zw** [comment]
The v2 will do minimal edits to your route rules, the only time it will, will be for optimizing how some module asset is being used.

For example, with Sitemaps we use route rules to set appropriate cache headers on the sitemap URLs.
