### ISSUE TITLE
Nuxt SEO Kit nitro function too big on vercel edge

### ISSUE THREAD

**Issue by ThimoDEV** [harlan-zw/nuxt-seo#73]
### Describe the bug

Nuxt SEO Kit making the default nitro edge function

`The Edge Function "__nitro" size is 1.35 MB and your plan size limit is 1 MB. `

![image](https://github.com/harlan-zw/nuxt-seo-kit/assets/68739517/8eb62fc8-01f1-485b-a7e5-c279f9b96fdd)

The nitro server.mjs file size gets doubled when nuxt seo kit gets added to a project

### Reproduction

```Shell
https://github.com/ThimoDEV/nuxt-content-repro

The naming of this repo might be a bit odd, but I added vercel-edge as nitro config to demonstrate:

To reproduce:

- Clone project
- Deploy on Vercel
- Notice function __nitro error
```

### System / Nuxt Info
- Vercel
- Windows 10
- nuxt 3.6.2 and 3.6.3

**Comment by harlan-zw** [comment]
You will need to disable runtime `ogImage` if you want to get under 1mb.

```ts
export default {
  ogImage: {
    enabled: false,
  }
}
```
