### ISSUE TITLE
Add links to corresponding project in docs

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-seo#89]
### Clear and concise description of the problem

Hello,

Each time I want to report an issue, I create a stackblitz, go to nuxtseo.com, install module and create the reproduction.

Then, I want to report the issue but I struggle to find the repo since there is no links in the docs to the corresponding project. 

### Suggested solution

I think it could be good to add links to each repo in the documentation.

**Comment by harlan-zw** [comment]
Agreed, the v2 workflow is not ideal at the moment. Docs will exist in their own repo at some point.

**Comment by Barbapapazes** [comment]
> Agreed, the v2 workflow is not ideal at the moment. Docs will exist in their own repo at some point.

Do you want to split docs into each package repo and use `unstorage` to use it on `nuxtseo.com`? 

Another point, I think that it is important to have, on documentation, a list of links to each repo since there is 2 or 3 for schema-org for example.

If you want help to improve docs, ping me!

**Comment by harlan-zw** [comment]
> > Agreed, the v2 workflow is not ideal at the moment. Docs will exist in their own repo at some point.
> 
> Do you want to split docs into each package repo and use `unstorage` to use it on `nuxtseo.com`?
> 
> Another point, I think that it is important to have, on documentation, a list of links to each repo since there is 2 or 3 for schema-org for example.
> 
> If you want help to improve docs, ping me!

Once docs are stable I think this is a great idea :+1: I don't think I can offer v1 docs as they only existed within the read me file and I can't be bothered to port them.

**Comment by harlan-zw** [comment]
I think this should be well solved now within the docs, also each module has a DevTool integrationwhich has a link to create an issue.

> Do you want to split docs into each package repo and use unstorage to use it on nuxtseo.com?

This is still something I'd like to explore but still a lot more I want to do with the docs before this
